package com.ets.fe.pnr.gui;

import com.ets.fe.DashBoardFrame;
import com.ets.fe.a_maintask.CompletePnrTask;
import com.ets.fe.acdoc.gui.InvoiceDlg;
import com.ets.fe.client.gui.AgentFrame;
import com.ets.fe.os.gui.OtherServiceDlg;
import com.ets.fe.os.gui.OtherServiceUpdateTask;
import com.ets.fe.os.model.OtherService;
import com.ets.fe.pnr.model.Itinerary;
import com.ets.fe.pnr.model.Pnr;
import com.ets.fe.pnr.model.Ticket;
import com.ets.fe.util.DateUtil;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Window;
import java.awt.font.TextAttribute;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Yusuf
 */
public class PnrPanel extends JPanel implements PropertyChangeListener {

    private final DashBoardFrame parent;
    private boolean saveNeeded;
   
    private Pnr pnr;
    private final Long pnrId;
    private List<Ticket> tickets;
    private Ticket ticket;
    private List<Itinerary> segments;

    private CompletePnrTask completePnrTask;

    public PnrPanel(Long pnrId, DashBoardFrame parent) {
        this.parent = parent;
        this.pnrId = pnrId;
        initComponents();
        completePnrTask = new CompletePnrTask(pnrId, progressBar);
        completePnrTask.addPropertyChangeListener(this);
        completePnrTask.execute();

    }

//    private void getPnr() {
//        pnr.setBookingAgtOid(txtBookingOID.getText().trim());
//        pnr.setTicketingAgtOid();
//        pnr.setPnrCreatorAgentSine();
//        pnr.setTicketingAgentSine();
//        pnr.setVendorPNR();
//        pnr.setAirLineCode();
//        pnr.setNoOfPax().toString();
//        pnr.setPnrCreationDate();
//    }

    private void populatePnr() {
        lblPnr.setText(pnr.getGdsPnr());
        txtBookingOID.setText(pnr.getBookingAgtOid());
        txtTicketingOID.setText(pnr.getTicketingAgtOid());
        txtBAgentSine.setText(pnr.getPnrCreatorAgentSine());
        txtTAgentSine.setText(pnr.getTicketingAgentSine());
        txtVendorPNR.setText(pnr.getVendorPNR());
        txtAirline.setText(pnr.getAirLineCode());
        txtTotalPsgr.setText(pnr.getNoOfPax().toString());
        dtBookingDate.setDate(pnr.getPnrCreationDate());
    }

    private void populateTblTicket() {

        tblTicket.clearSelection();
        DefaultTableModel model = (DefaultTableModel) tblTicket.getModel();
        model.getDataVector().removeAllElements();

        int row = 0;
        BigDecimal totalPurchase = new BigDecimal("0.00");
        BigDecimal totalSelling = new BigDecimal("0.00");
        BigDecimal tCom = new BigDecimal("0.00");
        BigDecimal tNetPayable = new BigDecimal("0.00");
        BigDecimal tPL = new BigDecimal("0.00");

        for (Ticket t : this.tickets) {
            boolean invoiced = true;
            if (t.getTicketingSalesAcDoc() == null) {
                invoiced = false;
            } else {
                invoiced = true;
            }
            totalPurchase = totalPurchase.add(t.calculateNetPurchaseFare());
            totalSelling = totalSelling.add(t.calculateNetSellingFare());

            model.insertRow(row, new Object[]{t.getFullPaxNameWithPaxNo(),
                t.getTktStatus(), t.getBaseFare(), t.getTax(), t.getCommission(), t.calculateNetPurchaseFare(),
                t.getGrossFare(), t.getDiscount(), t.calculateNetSellingFare(),
                t.calculateRevenue(), invoiced});

            row++;
        }

        model.addRow(new Object[]{"Totals", "", "", "", "", "", totalPurchase, "", "", "", totalSelling});

        //tblTicket.setRowSelectionInterval(this.tickets.indexOf(this.ticket), this.tickets.indexOf(this.ticket));
    }

    public void newTSalesInvoice() {

        Window w = SwingUtilities.getWindowAncestor(this);
        Frame owner = w instanceof Frame ? (Frame) w : null;
        InvoiceDlg dlg = new InvoiceDlg(owner);
        dlg.setLocationRelativeTo(this);
        dlg.setTitle("New Invoice");

        if (dlg.showDialog(null)) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CommandPanel = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnCreateInvoice = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        TopPanel = new javax.swing.JPanel();
        PnrPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBookingOID = new javax.swing.JTextField();
        txtBAgentSine = new javax.swing.JTextField();
        txtVendorPNR = new javax.swing.JTextField();
        txtTicketingOID = new javax.swing.JTextField();
        txtAirline = new javax.swing.JTextField();
        txtTAgentSine = new javax.swing.JTextField();
        txtTotalPsgr = new javax.swing.JTextField();
        dtBookingDate = new org.jdesktop.swingx.JXDatePicker();
        lblPnr = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        accountingDocumentsComponent1 = new com.ets.fe.components.AccountingDocumentsComponent();
        TicketPanel = new javax.swing.JPanel();
        tblSegment = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicket = new JXTable(){public Component prepareRenderer(TableCellRenderer renderer,
            int rowIndex, int vColIndex) {
            Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);                     
            String s = this.getModel().getValueAt(rowIndex, 1).toString();       

            if (s.equalsIgnoreCase("BOOK") ) {                
                c.setForeground(Color.yellow);
            } else if(s.equalsIgnoreCase("ISSUE")){
                c.setForeground(Color.green);
            }else if(s.equalsIgnoreCase("REISSUE")){
                c.setForeground(Color.cyan);
            }else if(s.equalsIgnoreCase("REFUND")){
                c.setForeground(Color.red);
            }else if(s.equalsIgnoreCase("VOID")){
                c.setForeground(Color.ORANGE);
                Map  attributes = c.getFont().getAttributes();
                attributes.put(TextAttribute.STRIKETHROUGH, TextAttribute.STRIKETHROUGH_ON);
                Font newFont = new Font(attributes);
                c.setFont(newFont);
            }else{
                c.setForeground(Color.WHITE);
            }
            return c;
        }
    };
    ticketComponent = new com.ets.fe.components.TicketComponent();
    jPanel1 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    TicketingAgtPanel = new javax.swing.JPanel();
    jComboBox2 = new javax.swing.JComboBox();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();
    jXBusyLabel2 = new org.jdesktop.swingx.JXBusyLabel();
    jButton2 = new javax.swing.JButton();
    clientSearchComponent1 = new com.ets.fe.components.ClientSearchComponent();
    progressBar = new javax.swing.JProgressBar();

    CommandPanel.setBackground(new java.awt.Color(102, 102, 102));
    CommandPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    CommandPanel.setPreferredSize(new java.awt.Dimension(441, 35));
    CommandPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 2, 2));

    jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SCNote24.png"))); // NOI18N
    jButton10.setPreferredSize(new java.awt.Dimension(57, 30));
    CommandPanel.add(jButton10);

    jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/SDNote24.png"))); // NOI18N
    jButton11.setPreferredSize(new java.awt.Dimension(57, 30));
    CommandPanel.add(jButton11);

    jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/STCrn24.png"))); // NOI18N
    jButton9.setPreferredSize(new java.awt.Dimension(57, 30));
    CommandPanel.add(jButton9);

    btnCreateInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/STInv24.png"))); // NOI18N
    btnCreateInvoice.setPreferredSize(new java.awt.Dimension(57, 30));
    btnCreateInvoice.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCreateInvoiceActionPerformed(evt);
        }
    });
    CommandPanel.add(btnCreateInvoice);

    btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh24.png"))); // NOI18N
    btnRefresh.setPreferredSize(new java.awt.Dimension(57, 30));
    btnRefresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefreshActionPerformed(evt);
        }
    });
    CommandPanel.add(btnRefresh);

    btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save24.png"))); // NOI18N
    btnSave.setPreferredSize(new java.awt.Dimension(57, 30));
    btnSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveActionPerformed(evt);
        }
    });
    CommandPanel.add(btnSave);

    jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit24.png"))); // NOI18N
    jButton7.setPreferredSize(new java.awt.Dimension(57, 30));
    CommandPanel.add(jButton7);

    jSplitPane1.setDividerLocation(1010);
    jSplitPane1.setDividerSize(4);
    jSplitPane1.setResizeWeight(0.8);

    jSplitPane2.setDividerLocation(205);
    jSplitPane2.setDividerSize(4);
    jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
    jSplitPane2.setResizeWeight(0.2);

    PnrPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PNR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
    PnrPanel.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("BookingOID");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel1, gridBagConstraints);

    jLabel2.setText("B.Agt Sine");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel2, gridBagConstraints);

    jLabel3.setText("Vendor PNR");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel3, gridBagConstraints);

    jLabel4.setText("TicketingOID");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel4, gridBagConstraints);

    jLabel5.setText("T.Agt Sine");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel5, gridBagConstraints);

    jLabel6.setText("Airline");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel6, gridBagConstraints);

    jLabel7.setText("Total Psgr");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel7, gridBagConstraints);

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel9.setText("Booking Date");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(jLabel9, gridBagConstraints);

    txtBookingOID.setEditable(false);
    txtBookingOID.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtBookingOIDFocusLost(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(txtBookingOID, gridBagConstraints);

    txtBAgentSine.setEditable(false);
    txtBAgentSine.setToolTipText("PNR Creator Agent Sine ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(txtBAgentSine, gridBagConstraints);

    txtVendorPNR.setEditable(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(txtVendorPNR, gridBagConstraints);

    txtTicketingOID.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtTicketingOIDFocusLost(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(txtTicketingOID, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(txtAirline, gridBagConstraints);

    txtTAgentSine.setEditable(false);
    txtTAgentSine.setToolTipText("Ticketing Agent Sine");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(txtTAgentSine, gridBagConstraints);

    txtTotalPsgr.setEditable(false);
    txtTotalPsgr.setToolTipText("Total number of passengers in PNR ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(txtTotalPsgr, gridBagConstraints);

    dtBookingDate.setPreferredSize(new java.awt.Dimension(108, 21));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    PnrPanel.add(dtBookingDate, gridBagConstraints);

    lblPnr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lblPnr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    lblPnr.setText("PNR");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 4, 2);
    PnrPanel.add(lblPnr, gridBagConstraints);

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accounting Documents", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(accountingDocumentsComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(accountingDocumentsComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
    TopPanel.setLayout(TopPanelLayout);
    TopPanelLayout.setHorizontalGroup(
        TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TopPanelLayout.createSequentialGroup()
            .addComponent(PnrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    TopPanelLayout.setVerticalGroup(
        TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(PnrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jSplitPane2.setTopComponent(TopPanel);

    tblSegment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

    jScrollPane1.setBorder(null);

    tblTicket.setBackground(new java.awt.Color(0, 0, 0));
    tblTicket.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "P.Name", "Status", "Base Fare", "Tax", "Com", "Net.Fare", "G.Selling", "Disc", "NetSelling", "Rev", "Inv"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false, false, false, false, false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tblTicket.setEditable(false);
    tblTicket.setSelectionBackground(new java.awt.Color(146, 119, 119));
    tblTicket.setSortable(false);
    tblTicket.getTableHeader().setReorderingAllowed(false);
    tblTicket.getSelectionModel().addListSelectionListener(tblTicketListener);
    jScrollPane1.setViewportView(tblTicket);
    if (tblTicket.getColumnModel().getColumnCount() > 0) {
        tblTicket.getColumnModel().getColumn(0).setPreferredWidth(120);
        tblTicket.getColumnModel().getColumn(4).setMinWidth(55);
        tblTicket.getColumnModel().getColumn(4).setPreferredWidth(55);
        tblTicket.getColumnModel().getColumn(4).setMaxWidth(65);
        tblTicket.getColumnModel().getColumn(7).setMinWidth(55);
        tblTicket.getColumnModel().getColumn(7).setPreferredWidth(55);
        tblTicket.getColumnModel().getColumn(7).setMaxWidth(65);
        tblTicket.getColumnModel().getColumn(10).setMinWidth(30);
        tblTicket.getColumnModel().getColumn(10).setPreferredWidth(25);
        tblTicket.getColumnModel().getColumn(10).setMaxWidth(30);
    }

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(ticketComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(ticketComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
    );

    tblSegment.addTab("Tickets", jPanel4);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 978, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 259, Short.MAX_VALUE)
    );

    tblSegment.addTab("Segments", jPanel1);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 978, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 259, Short.MAX_VALUE)
    );

    tblSegment.addTab("Remarks", jPanel5);

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refund.png"))); // NOI18N
    jButton1.setPreferredSize(new java.awt.Dimension(55, 30));

    jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/void24.png"))); // NOI18N
    jButton3.setPreferredSize(new java.awt.Dimension(55, 30));

    jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plus24.png"))); // NOI18N
    jButton4.setPreferredSize(new java.awt.Dimension(55, 30));

    jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
    jButton5.setPreferredSize(new java.awt.Dimension(55, 30));

    jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/details.png"))); // NOI18N
    jButton6.setPreferredSize(new java.awt.Dimension(55, 30));

    javax.swing.GroupLayout TicketPanelLayout = new javax.swing.GroupLayout(TicketPanel);
    TicketPanel.setLayout(TicketPanelLayout);
    TicketPanelLayout.setHorizontalGroup(
        TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TicketPanelLayout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tblSegment))
    );
    TicketPanelLayout.setVerticalGroup(
        TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(TicketPanelLayout.createSequentialGroup()
            .addGap(1, 1, 1)
            .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TicketPanelLayout.createSequentialGroup()
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addComponent(tblSegment, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
    );

    jSplitPane2.setRightComponent(TicketPanel);

    jSplitPane1.setLeftComponent(jSplitPane2);

    TicketingAgtPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ticketing Agent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
    TicketingAgtPanel.setLayout(new java.awt.GridBagLayout());

    jComboBox2.setMaximumSize(new java.awt.Dimension(32767, 19));
    jComboBox2.setMinimumSize(new java.awt.Dimension(28, 19));
    jComboBox2.setPreferredSize(new java.awt.Dimension(28, 19));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 0, 4, 0);
    TicketingAgtPanel.add(jComboBox2, gridBagConstraints);

    jTextArea2.setColumns(20);
    jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
    jTextArea2.setLineWrap(true);
    jTextArea2.setRows(5);
    jScrollPane2.setViewportView(jTextArea2);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
    TicketingAgtPanel.add(jScrollPane2, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
    TicketingAgtPanel.add(jXBusyLabel2, gridBagConstraints);

    jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh24.png"))); // NOI18N
    jButton2.setPreferredSize(new java.awt.Dimension(40, 33));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
    TicketingAgtPanel.add(jButton2, gridBagConstraints);

    progressBar.setMaximumSize(new java.awt.Dimension(146, 18));
    progressBar.setMinimumSize(new java.awt.Dimension(146, 18));
    progressBar.setPreferredSize(new java.awt.Dimension(146, 18));
    progressBar.setStringPainted(true);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(clientSearchComponent1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(TicketingAgtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
            .addGap(4, 4, 4))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addComponent(clientSearchComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(TicketingAgtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
            .addGap(23, 23, 23)
            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(4, 4, 4))
    );

    jSplitPane1.setRightComponent(jPanel2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jSplitPane1)
        .addComponent(CommandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(CommandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSplitPane1))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        completePnrTask = new CompletePnrTask(pnrId, progressBar);
        completePnrTask.addPropertyChangeListener(this);
        completePnrTask.execute();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCreateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateInvoiceActionPerformed
        newTSalesInvoice();
    }//GEN-LAST:event_btnCreateInvoiceActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtBookingOIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBookingOIDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookingOIDFocusLost

    private void txtTicketingOIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTicketingOIDFocusLost
        String val = txtTicketingOID.getText();
        if (val != null && !val.isEmpty()) {           
            this.pnr.setTicketingAgtOid(val.trim());
             txtTicketingOID.setBackground(Color.WHITE);
        }else{         
         txtTicketingOID.setBackground(Color.YELLOW);
         txtTicketingOID.requestFocus();
        }
    }//GEN-LAST:event_txtTicketingOIDFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CommandPanel;
    private javax.swing.JPanel PnrPanel;
    private javax.swing.JPanel TicketPanel;
    private javax.swing.JPanel TicketingAgtPanel;
    private javax.swing.JPanel TopPanel;
    private com.ets.fe.components.AccountingDocumentsComponent accountingDocumentsComponent1;
    private javax.swing.JButton btnCreateInvoice;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private com.ets.fe.components.ClientSearchComponent clientSearchComponent1;
    private org.jdesktop.swingx.JXDatePicker dtBookingDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextArea jTextArea2;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel2;
    private javax.swing.JLabel lblPnr;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTabbedPane tblSegment;
    private org.jdesktop.swingx.JXTable tblTicket;
    private com.ets.fe.components.TicketComponent ticketComponent;
    private javax.swing.JTextField txtAirline;
    private javax.swing.JTextField txtBAgentSine;
    private javax.swing.JTextField txtBookingOID;
    private javax.swing.JTextField txtTAgentSine;
    private javax.swing.JTextField txtTicketingOID;
    private javax.swing.JTextField txtTotalPsgr;
    private javax.swing.JTextField txtVendorPNR;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress".equals(evt.getPropertyName())) {
            int progress = (Integer) evt.getNewValue();
            progressBar.setValue(progress);
            if (progress == 100) {
                try {
                    pnr = completePnrTask.get();
                    tickets = pnr.getTickets();
                    segments = pnr.getSegments();
                    populatePnr();
                    populateTblTicket();
                    //populateTblAgent();
                } catch (InterruptedException ex) {
                    Logger.getLogger(AgentFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ExecutionException ex) {
                    Logger.getLogger(AgentFrame.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //btnSearch.setEnabled(true);
                }
            }
        }
    }

    private ListSelectionListener tblTicketListener = new ListSelectionListener() {

        public void valueChanged(ListSelectionEvent e) {
            if (e.getValueIsAdjusting()) {
                return;
            }
            int selectedRow = tblTicket.getSelectedRow();
            if (selectedRow != -1 && selectedRow != tblTicket.getRowCount() - 1) {
                ticket = tickets.get(selectedRow);
                ticketComponent.displayTicket(ticket);
            }
        }
    };

    private void setSaveNeeded(boolean saveNeeded) {
        if (saveNeeded != this.saveNeeded) {
            this.saveNeeded = saveNeeded;
        }
        if (this.saveNeeded == true) {
            btnSave.setEnabled(true);
        } else {
            btnSave.setEnabled(false);
        }
    }
}
