package com.ets.fe.pnr.gui;

import com.ets.fe.pnr.task.SegmentReportTask;
import com.ets.fe.report.model.SegmentReport;
import com.ets.fe.report.model.SegmentReport.Segment;
import com.ets.fe.util.DateUtil;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Yusuf
 */
public class SegmentReportFrame extends JInternalFrame implements PropertyChangeListener {

    private JDesktopPane desktopPane;
    SegmentReportTask task;
    List<Segment> list = new ArrayList<>();

    public SegmentReportFrame(JDesktopPane desktopPane) {
        initComponents();
        this.desktopPane = desktopPane;
        dtFrom.setDate(DateUtil.getBeginingOfMonth());
        dtTo.setDate(DateUtil.getEndOfMonth());
    }

    private void buttonSearchActionPerformed(ActionEvent event) {

        String ticketStatus = (String) cmbTicketStatus.getSelectedItem();
        String airLineCode = txtCareerCode.getText();
        String ticketingAgtOid = txtOfficeId.getText();

        Date from = dtFrom.getDate();
        Date to = dtTo.getDate();

        if ("All".equals(ticketStatus)) {
            ticketStatus = null;
        }

        if (airLineCode.isEmpty()) {
            airLineCode = null;
        }

        if (airLineCode == null || ticketingAgtOid.isEmpty()) {
            ticketingAgtOid = null;
        }

        if (airLineCode == null || airLineCode.isEmpty()) {
            airLineCode = null;
        }

        progressBar.setValue(0);

        task = new SegmentReportTask(ticketStatus, airLineCode, from, to, ticketingAgtOid);
        task.addPropertyChangeListener(this);
        task.execute();
    }

    private void populateTblSegment() {
        SegmentReport report = task.getReport();

        List<Segment> list = report.getList();
        DefaultTableModel tableModel = (DefaultTableModel) tblSegment.getModel();
        tableModel.getDataVector().removeAllElements();
        tblSegment.repaint();
        int row = 0;
        if (list.size() > 0) {
            for (Segment s : list) {
                tableModel.insertRow(row, new Object[]{s.getTravelDate(), s.getOutCity(), s.getInCity(), s.getFlightNo(),
                    s.getAirLine(), s.getTicketClass(), s.getBookingOid(), s.getTicketingOid(), s.getPnr(),
                    s.getTicketNo(), s.getTktStatus(), s.getCount()});
                row++;
            }
        } else {
            tableModel.insertRow(0, new Object[]{});
        }
        lblIssue.setText(report.getTotalIssuedSegment().toString());
        lblCancell.setText(report.getTotalRefundedSegment().toString());
        lblOpen.setText(report.getTotalOpenSegment().toString());
        lblVoid.setText(report.getTotalVoidSegment().toString());
        lblReissue.setText(report.getTotalReissuedSegment().toString());
        lblBalance.setText(report.getSegBalance().toString());
        btnSearch.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbTicketStatus = new javax.swing.JComboBox();
        txtCareerCode = new javax.swing.JTextField();
        txtOfficeId = new javax.swing.JTextField();
        dtFrom = new org.jdesktop.swingx.JXDatePicker();
        dtTo = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblIssue = new javax.swing.JLabel();
        lblCancell = new javax.swing.JLabel();
        lblOpen = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblVoid = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblReissue = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSegment = new JXTable(){public Component prepareRenderer(TableCellRenderer renderer,
            int rowIndex, int vColIndex) {
            Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);  
            String s = "";
            Object o = tblSegment.getModel().getValueAt(rowIndex, 10);       
            if(o!=null){
                s = o.toString();
            }
            if (s.equalsIgnoreCase("BOOK") ) {                
                c.setForeground(Color.yellow);
            } else if(s.equalsIgnoreCase("ISSUE")){
                c.setForeground(Color.green);
            }else if(s.equalsIgnoreCase("REISSUE")){
                c.setForeground(Color.cyan);
            }else if(s.equalsIgnoreCase("REFUND")){
                c.setForeground(Color.red);
            }else if(s.equalsIgnoreCase("VOID")){
                c.setForeground(Color.ORANGE);
            }else{
                c.setForeground(Color.WHITE);
            }
            return c;
        }
    };
    jPanel3 = new javax.swing.JPanel();
    progressBar = new javax.swing.JProgressBar();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel9 = new javax.swing.JLabel();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("Segment Report");
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("Ticket Status");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(jLabel1, gridBagConstraints);

    jLabel2.setText("Office Id");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(jLabel2, gridBagConstraints);

    jLabel3.setText("Date To");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(jLabel3, gridBagConstraints);

    cmbTicketStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "ISSUE", "REISSUE", "REFUND", "VOID" }));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(cmbTicketStatus, gridBagConstraints);

    txtCareerCode.setColumns(20);
    txtCareerCode.setToolTipText("Separated by comma, Example: SV,EK,BA");
    txtCareerCode.setMinimumSize(new java.awt.Dimension(200, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(txtCareerCode, gridBagConstraints);

    txtOfficeId.setColumns(20);
    txtOfficeId.setToolTipText("Ticketing agent office Id, Separated by comma, Example: ABC123AB,CDE123CD");
    txtOfficeId.setMinimumSize(new java.awt.Dimension(200, 20));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(txtOfficeId, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(dtFrom, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(dtTo, gridBagConstraints);

    jLabel4.setText("Date From");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(jLabel4, gridBagConstraints);

    btnSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search18.png"))); // NOI18N
    btnSearch.setText("Search");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSearchActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(btnSearch, gridBagConstraints);

    jLabel5.setText("Airline Code");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
    jPanel1.add(jLabel5, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 1, 0);
    getContentPane().add(jPanel1, gridBagConstraints);

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Summery", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

    jLabel6.setText("Total Issued");

    jLabel7.setText("Total Cancelled");

    jLabel8.setText("Total Void");

    lblIssue.setText("0");

    lblCancell.setText("0");

    lblOpen.setText("0");

    jLabel12.setText("Total Open");

    lblVoid.setText("0");

    jLabel14.setText("Total Re Issued");

    lblReissue.setText("0");

    jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel16.setText("Ballance");

    lblBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    lblBalance.setText("0");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lblOpen, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addComponent(lblCancell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblReissue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(lblVoid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGap(22, 22, 22))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(lblIssue)
                .addComponent(jLabel8)
                .addComponent(lblVoid))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(lblCancell)
                .addComponent(jLabel14)
                .addComponent(lblReissue))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOpen)
                    .addComponent(jLabel12))
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lblBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.weightx = 0.5;
    gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
    getContentPane().add(jPanel2, gridBagConstraints);

    tblSegment.setBackground(new java.awt.Color(0, 0, 0));
    tblSegment.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Travel Date", "Out City", "In City", "Fl No", "Airline", "Class", "Booking OID", "Effecting OID", "Pnr", "Ticket Number", "Status", ""
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false, false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    tblSegment.getTableHeader().setReorderingAllowed(false);
    jScrollPane1.setViewportView(tblSegment);
    if (tblSegment.getColumnModel().getColumnCount() > 0) {
        tblSegment.getColumnModel().getColumn(0).setResizable(false);
        tblSegment.getColumnModel().getColumn(0).setPreferredWidth(70);
        tblSegment.getColumnModel().getColumn(1).setResizable(false);
        tblSegment.getColumnModel().getColumn(1).setPreferredWidth(60);
        tblSegment.getColumnModel().getColumn(2).setResizable(false);
        tblSegment.getColumnModel().getColumn(2).setPreferredWidth(60);
        tblSegment.getColumnModel().getColumn(3).setResizable(false);
        tblSegment.getColumnModel().getColumn(3).setPreferredWidth(60);
        tblSegment.getColumnModel().getColumn(4).setResizable(false);
        tblSegment.getColumnModel().getColumn(4).setPreferredWidth(60);
        tblSegment.getColumnModel().getColumn(5).setResizable(false);
        tblSegment.getColumnModel().getColumn(5).setPreferredWidth(60);
        tblSegment.getColumnModel().getColumn(6).setResizable(false);
        tblSegment.getColumnModel().getColumn(6).setPreferredWidth(100);
        tblSegment.getColumnModel().getColumn(7).setResizable(false);
        tblSegment.getColumnModel().getColumn(7).setPreferredWidth(100);
        tblSegment.getColumnModel().getColumn(8).setResizable(false);
        tblSegment.getColumnModel().getColumn(8).setPreferredWidth(100);
        tblSegment.getColumnModel().getColumn(9).setResizable(false);
        tblSegment.getColumnModel().getColumn(10).setResizable(false);
        tblSegment.getColumnModel().getColumn(10).setPreferredWidth(45);
        tblSegment.getColumnModel().getColumn(11).setResizable(false);
        tblSegment.getColumnModel().getColumn(11).setPreferredWidth(20);
    }

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
    getContentPane().add(jScrollPane1, gridBagConstraints);

    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    jPanel3.setMaximumSize(new java.awt.Dimension(32767, 24));
    jPanel3.setPreferredSize(new java.awt.Dimension(980, 24));
    jPanel3.setLayout(new java.awt.GridBagLayout());

    progressBar.setMaximumSize(new java.awt.Dimension(32767, 18));
    progressBar.setMinimumSize(new java.awt.Dimension(10, 18));
    progressBar.setPreferredSize(new java.awt.Dimension(146, 18));
    progressBar.setStringPainted(true);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
    jPanel3.add(progressBar, gridBagConstraints);

    jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
    jPanel3.add(jSeparator1, gridBagConstraints);

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel9.setText("Message:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(1, 2, 1, 2);
    jPanel3.add(jLabel9, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    getContentPane().add(jPanel3, gridBagConstraints);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        buttonSearchActionPerformed(evt);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbTicketStatus;
    private org.jdesktop.swingx.JXDatePicker dtFrom;
    private org.jdesktop.swingx.JXDatePicker dtTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblCancell;
    private javax.swing.JLabel lblIssue;
    private javax.swing.JLabel lblOpen;
    private javax.swing.JLabel lblReissue;
    private javax.swing.JLabel lblVoid;
    private javax.swing.JProgressBar progressBar;
    private org.jdesktop.swingx.JXTable tblSegment;
    private javax.swing.JTextField txtCareerCode;
    private javax.swing.JTextField txtOfficeId;
    // End of variables declaration//GEN-END:variables
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress" == evt.getPropertyName()) {
            int progress = (Integer) evt.getNewValue();
            progressBar.setValue(progress);
            if (progress == 100) {
                populateTblSegment();
            }
        }
    }
}
