package com.ets.fe.acdoc.gui.comp;

import com.ets.fe.acdoc.model.AccountingDocument;
import com.ets.fe.acdoc_o.model.OtherSalesAcDoc;
import com.ets.fe.acdoc.model.TicketingPurchaseAcDoc;
import com.ets.fe.acdoc.model.TicketingSalesAcDoc;
import com.ets.fe.util.DateUtil;
import com.ets.fe.util.Enums;
import javax.swing.JPanel;

/**
 *
 * @author Yusuf
 */
public class AcDocHeaderComponent extends JPanel {

    private AccountingDocument doc;

    public AcDocHeaderComponent() {
        initComponents();
    }

    public void display(AccountingDocument doc) {
        this.doc = doc;
        if (doc.getId() == null || doc.getStatus().equals(Enums.AcDocStatus.VOID)) {
            cmbTerms.setEnabled(true);
        } else {
            cmbTerms.setEnabled(false);
        }

        txtUser.setText(doc.getCreatedByName());
        if (doc instanceof TicketingSalesAcDoc || doc instanceof OtherSalesAcDoc) {
            txtVendorRef.setVisible(false);
            lblVendorRef.setVisible(false);
        } else if (doc instanceof TicketingPurchaseAcDoc) {
            TicketingPurchaseAcDoc temp = (TicketingPurchaseAcDoc) doc;
            txtVendorRef.setVisible(true);
            lblVendorRef.setVisible(true);
            txtVendorRef.setText(temp.getVendorRef());
            cmbTerms.setEnabled(true);
        } else if (doc instanceof OtherSalesAcDoc) {
            txtVendorRef.setVisible(false);
            lblVendorRef.setVisible(false);
        }

        if (doc.getDocIssueDate() != null) {
            txtIssueDate.setText(DateUtil.dateToString(doc.getDocIssueDate()));
        }
        if (doc.getReference() != null) {
            txtInvRef.setText(doc.getReference().toString());
        }

        if (doc.getTerms() != null) {
            cmbTerms.setSelectedItem(doc.getTerms());
        } else {
            if (doc instanceof OtherSalesAcDoc) {
                OtherSalesAcDoc d = (OtherSalesAcDoc) doc;
                if (d.getCustomer() == null) {
                    cmbTerms.setSelectedItem("End of Month");
                } else {
                    cmbTerms.setSelectedIndex(0);
                }
            } else {
                if (doc.getPnr().getCustomer() == null) {
                    cmbTerms.setSelectedItem("End of Month");
                } else {
                    cmbTerms.setSelectedIndex(0);
                }
            }
        }
    }

    public AccountingDocument getDocument() {
        doc.setCreatedOn(doc.getDocIssueDate());
        doc.setTerms((String) cmbTerms.getSelectedItem());
        return doc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInvRef = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        cmbTerms = new javax.swing.JComboBox();
        lblVendorRef = new javax.swing.JLabel();
        txtVendorRef = new javax.swing.JTextField();
        txtIssueDate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Date");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 2, 2);
        add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Refference");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Terms *");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Issued By");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(jLabel4, gridBagConstraints);

        txtInvRef.setEditable(false);
        txtInvRef.setBackground(new java.awt.Color(0, 51, 51));
        txtInvRef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtInvRef.setForeground(new java.awt.Color(255, 255, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(txtInvRef, gridBagConstraints);

        txtUser.setEditable(false);
        txtUser.setBackground(new java.awt.Color(0, 51, 51));
        txtUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(txtUser, gridBagConstraints);

        cmbTerms.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbTerms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "End of Month", "Payment in Advance", "Cash with Order", "Cash on Delivery", "Net 7", "Net 10", "Net 60", "Net 90" }));
        cmbTerms.setMaximumSize(new java.awt.Dimension(32767, 19));
        cmbTerms.setMinimumSize(new java.awt.Dimension(28, 19));
        cmbTerms.setPreferredSize(new java.awt.Dimension(28, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(cmbTerms, gridBagConstraints);

        lblVendorRef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVendorRef.setText("Vendor Ref");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(lblVendorRef, gridBagConstraints);

        txtVendorRef.setBackground(new java.awt.Color(0, 51, 51));
        txtVendorRef.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVendorRef.setForeground(new java.awt.Color(255, 255, 0));
        txtVendorRef.setCaretColor(new java.awt.Color(255, 255, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(txtVendorRef, gridBagConstraints);

        txtIssueDate.setEditable(false);
        txtIssueDate.setBackground(new java.awt.Color(0, 51, 51));
        txtIssueDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtIssueDate.setForeground(new java.awt.Color(255, 255, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        add(txtIssueDate, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        add(jSeparator1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox cmbTerms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblVendorRef;
    private javax.swing.JTextField txtInvRef;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtUser;
    public static javax.swing.JTextField txtVendorRef;
    // End of variables declaration//GEN-END:variables

}
