/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgItinerary.java
 *
 * Created on 04-Jun-2011, 10:58:25
 */
package etsbackoffice.gui;

import etsbackoffice.ETSBackofficeApp;
import etsbackoffice.businesslogic.ItineraryBo;
import etsbackoffice.domain.Itinerary;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Yusuf
 */
public class DlgItinerary extends javax.swing.JDialog implements ActionListener{

    private ItineraryBo itineraryBo = (ItineraryBo) ETSBackofficeApp.getApplication().ctx.getBean("itineraryBo");
    private Itinerary segment;
    private boolean save;
    
    /** Creates new form DlgItinerary */
    public DlgItinerary(java.awt.Frame parent) {
        super(parent, "Flight Segment", true);
        initComponents();
        btnOk.addActionListener(this);
        CheckInput a = new CheckInput();
        txtMilage.setDocument(a);
    }

    public boolean showSegmentDialog(Itinerary s) {
        this.segment = s;

        populateSegment(this.segment);

        save = false;
        setLocationRelativeTo(this);
        setVisible(true);

        if (save) {            
            s.setDeptFrom(txtDptFrom.getText().trim());
            s.setDeptTo(txtDptTo.getText().trim());
            s.setDeptDate(txtDptDate.getText().trim());
            s.setDeptTime(txtDptTime.getText().trim());
            s.setArvDate(txtArvDate.getText().trim());
            s.setArvTime(txtArvTime.getText().trim());
            s.setTicketClass(txtClass.getText().trim());
            s.setFlightNo(txtFlNo.getText().trim());
            s.setTktStatus(txtStatus.getText().trim());
            s.setBaggage(txtBaggage.getText().trim());
            s.setAirLineID(txtCareer.getText().trim());
            s.setFlightDuration(txtFlDuration.getText().trim());
            s.setCheckInTerminal(txtChkInTerminal.getText().trim());
            s.setCheckInTime(txtChkInTime.getText().trim());
            s.setMealCode(txtMealCode.getText().trim());
            s.setMileage(Integer.valueOf(txtMilage.getText().trim()));
        }
        return save;
    }
    
    private void populateSegment(Itinerary s) {
        txtDptFrom.setText(s.getDeptFrom());
        txtDptTo.setText(s.getDeptTo());
        txtDptDate.setText(s.getDeptDate());
        txtDptTime.setText(s.getDeptTime());
        txtArvDate.setText(s.getArvDate());
        txtArvTime.setText(s.getArvTime());
        txtClass.setText(s.getTicketClass());
        txtFlNo.setText(s.getFlightNo());
        txtStatus.setText(s.getTktStatus());
        txtBaggage.setText(s.getBaggage());
        txtCareer.setText(s.getAirLineID());
        txtFlDuration.setText(s.getFlightDuration());
        txtChkInTerminal.setText(s.getCheckInTerminal());
        txtChkInTime.setText(s.getCheckInTime());
        txtMealCode.setText(s.getMealCode());
        txtMilage.setText(String.valueOf(s.getMileage()));
    }
    
    public void actionPerformed(ActionEvent evt) {
        Object source = evt.getSource();
        if (source == btnOk) {
            save = true;
            setVisible(false);
        } else {
            dispose();
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDptTo = new javax.swing.JTextField();
        txtDptDate = new javax.swing.JTextField();
        txtArvDate = new javax.swing.JTextField();
        txtDptFrom = new javax.swing.JTextField();
        txtDptTime = new javax.swing.JTextField();
        txtArvTime = new javax.swing.JTextField();
        txtCareer = new javax.swing.JTextField();
        txtFlNo = new javax.swing.JTextField();
        txtMealCode = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtBaggage = new javax.swing.JTextField();
        txtChkInTerminal = new javax.swing.JTextField();
        txtChkInTime = new javax.swing.JTextField();
        txtFlDuration = new javax.swing.JTextField();
        txtMilage = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 260));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(etsbackoffice.ETSBackofficeApp.class).getContext().getResourceMap(DlgItinerary.class);
        jLabel1.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel7, gridBagConstraints);

        jLabel8.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel10, gridBagConstraints);

        jLabel11.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel11, gridBagConstraints);

        jLabel12.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel12, gridBagConstraints);

        jLabel13.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel13, gridBagConstraints);

        jLabel14.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel14, gridBagConstraints);

        jLabel15.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel15, gridBagConstraints);

        jLabel16.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 4);
        getContentPane().add(jLabel16, gridBagConstraints);

        txtDptTo.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtDptTo.setText(resourceMap.getString("txtDptTo.text")); // NOI18N
        txtDptTo.setName("txtDptTo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtDptTo, gridBagConstraints);

        txtDptDate.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtDptDate.setText(resourceMap.getString("txtDptDate.text")); // NOI18N
        txtDptDate.setName("txtDptDate"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtDptDate, gridBagConstraints);

        txtArvDate.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtArvDate.setText(resourceMap.getString("txtArvDate.text")); // NOI18N
        txtArvDate.setName("txtArvDate"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtArvDate, gridBagConstraints);

        txtDptFrom.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtDptFrom.setText(resourceMap.getString("txtDptFrom.text")); // NOI18N
        txtDptFrom.setName("txtDptFrom"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(4, 2, 2, 2);
        getContentPane().add(txtDptFrom, gridBagConstraints);

        txtDptTime.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtDptTime.setText(resourceMap.getString("txtDptTime.text")); // NOI18N
        txtDptTime.setName("txtDptTime"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtDptTime, gridBagConstraints);

        txtArvTime.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtArvTime.setText(resourceMap.getString("txtArvTime.text")); // NOI18N
        txtArvTime.setName("txtArvTime"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtArvTime, gridBagConstraints);

        txtCareer.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtCareer.setText(resourceMap.getString("txtCareer.text")); // NOI18N
        txtCareer.setName("txtCareer"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtCareer, gridBagConstraints);

        txtFlNo.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtFlNo.setText(resourceMap.getString("txtFlNo.text")); // NOI18N
        txtFlNo.setName("txtFlNo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtFlNo, gridBagConstraints);

        txtMealCode.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtMealCode.setText(resourceMap.getString("txtMealCode.text")); // NOI18N
        txtMealCode.setName("txtMealCode"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtMealCode, gridBagConstraints);

        txtClass.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtClass.setText(resourceMap.getString("txtClass.text")); // NOI18N
        txtClass.setName("txtClass"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtClass, gridBagConstraints);

        txtStatus.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtStatus.setText(resourceMap.getString("txtStatus.text")); // NOI18N
        txtStatus.setName("txtStatus"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtStatus, gridBagConstraints);

        txtBaggage.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtBaggage.setText(resourceMap.getString("txtBaggage.text")); // NOI18N
        txtBaggage.setName("txtBaggage"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtBaggage, gridBagConstraints);

        txtChkInTerminal.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtChkInTerminal.setText(resourceMap.getString("txtChkInTerminal.text")); // NOI18N
        txtChkInTerminal.setName("txtChkInTerminal"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtChkInTerminal, gridBagConstraints);

        txtChkInTime.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtChkInTime.setText(resourceMap.getString("txtChkInTime.text")); // NOI18N
        txtChkInTime.setName("txtChkInTime"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtChkInTime, gridBagConstraints);

        txtFlDuration.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtFlDuration.setText(resourceMap.getString("txtFlDuration.text")); // NOI18N
        txtFlDuration.setName("txtFlDuration"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtFlDuration, gridBagConstraints);

        txtMilage.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        txtMilage.setText(resourceMap.getString("txtMilage.text")); // NOI18N
        txtMilage.setName("txtMilage"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtMilage, gridBagConstraints);

        jSeparator1.setName("jSeparator1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(jSeparator1, gridBagConstraints);

        jSeparator2.setName("jSeparator2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(jSeparator2, gridBagConstraints);

        jPanel1.setName("jPanel1"); // NOI18N

        btnOk.setFont(resourceMap.getFont("btnOk.font")); // NOI18N
        btnOk.setIcon(resourceMap.getIcon("btnOk.icon")); // NOI18N
        btnOk.setText(resourceMap.getString("btnOk.text")); // NOI18N
        btnOk.setMaximumSize(new java.awt.Dimension(70, 30));
        btnOk.setMinimumSize(new java.awt.Dimension(100, 35));
        btnOk.setName("btnOk"); // NOI18N
        btnOk.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel1.add(btnOk);

        btnCancel.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        btnCancel.setIcon(resourceMap.getIcon("btnCancel.icon")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setMaximumSize(new java.awt.Dimension(140, 35));
        btnCancel.setMinimumSize(new java.awt.Dimension(140, 35));
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 35));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DlgItinerary dialog = new DlgItinerary(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtArvDate;
    private javax.swing.JTextField txtArvTime;
    private javax.swing.JTextField txtBaggage;
    private javax.swing.JTextField txtCareer;
    private javax.swing.JTextField txtChkInTerminal;
    private javax.swing.JTextField txtChkInTime;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtDptDate;
    private javax.swing.JTextField txtDptFrom;
    private javax.swing.JTextField txtDptTime;
    private javax.swing.JTextField txtDptTo;
    private javax.swing.JTextField txtFlDuration;
    private javax.swing.JTextField txtFlNo;
    private javax.swing.JTextField txtMealCode;
    private javax.swing.JTextField txtMilage;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
