/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgLogin.java
 *
 * Created on 24-Jun-2011, 11:13:36
 */
package etsbackoffice.gui;

import etsbackoffice.ETSBackofficeApp;
import etsbackoffice.businesslogic.AuthenticationBo;
import etsbackoffice.businesslogic.MAgentBo;
import etsbackoffice.businesslogic.UserBo;
import etsbackoffice.domain.AppSettings;
import etsbackoffice.domain.MasterAgent;
import etsbackoffice.domain.User;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Yusuf
 */
public class DlgLogin extends javax.swing.JDialog implements ActionListener {

    Image img;
    AuthenticationBo authenticationBo;//  = (AuthenticationBo) ETSBackofficeApp.getApplication().ctx.getBean("authenticationBo");    
    MAgentBo mAgentBo;
    User user;
    AppSettings appSettings;
    private boolean login;

    /** Creates new form DlgLogin */
    public DlgLogin(java.awt.Frame parent) {
        super(parent, "Login", true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setLocation(screenWidth / 2 - 200, screenHeight / 2 - 200);
        initComponents();
        btnLogin.addActionListener(this);
        btnCancel.addActionListener(this);
    }

    public boolean showLoginDialog() {
        login = false;
        setLocationRelativeTo(this);
        setVisible(true);

        if (login) {
        }
        return login;
    }

    public boolean login(String userName, String password, String newPassword) {
        boolean authenticate = false;
        try {
            authenticationBo = (AuthenticationBo) ETSBackofficeApp.getApplication().ctx.getBean("authenticationBo");
            mAgentBo = (MAgentBo) ETSBackofficeApp.getApplication().ctx.getBean("mAgentBo");
            UserBo userBo = (UserBo) ETSBackofficeApp.getApplication().ctx.getBean("userBo");

            user = authenticationBo.checkLoginDetails(userName, password);
            if (user == null) {
                authenticate = false;
            } else {
                authenticate = true;
            }

            //return authenticate;
            if (authenticate) {
                if (!newPassword.isEmpty()) {
                    user.setPassword(newPassword);
                    userBo.setUser(user);
                    userBo.saveUser();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Wrong UserName or Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Login Exception", JOptionPane.WARNING_MESSAGE);
        }
        return authenticate;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        txtUserName = new javax.swing.JTextField();
        txtPWord = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        statusMessageLabel = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(503, 234));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        progressBar.setName("progressBar"); // NOI18N
        getContentPane().add(progressBar);
        progressBar.setBounds(326, 180, 170, 19);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(etsbackoffice.ETSBackofficeApp.class).getContext().getResourceMap(DlgLogin.class);
        txtUserName.setFont(resourceMap.getFont("txtUserName.font")); // NOI18N
        txtUserName.setName("txtUserName"); // NOI18N
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(300, 30, 180, 20);

        txtPWord.setFont(resourceMap.getFont("txtPWord.font")); // NOI18N
        txtPWord.setName("txtPWord"); // NOI18N
        txtPWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPWordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPWord);
        txtPWord.setBounds(300, 55, 180, 20);

        txtNewPassword.setFont(resourceMap.getFont("txtNewPassword.font")); // NOI18N
        txtNewPassword.setName("txtNewPassword"); // NOI18N
        txtNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtNewPassword);
        txtNewPassword.setBounds(300, 80, 180, 20);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(90, 15));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 70, 20);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(90, 15));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 55, 80, 20);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 15));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 80, 90, 20);

        btnLogin.setFont(resourceMap.getFont("btnLogin.font")); // NOI18N
        btnLogin.setText(resourceMap.getString("btnLogin.text")); // NOI18N
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.setPreferredSize(new java.awt.Dimension(90, 25));
        getContentPane().add(btnLogin);
        btnLogin.setBounds(300, 110, 90, 25);

        btnCancel.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.setPreferredSize(new java.awt.Dimension(90, 25));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(400, 110, 80, 25);

        statusMessageLabel.setFont(resourceMap.getFont("statusMessageLabel.font")); // NOI18N
        statusMessageLabel.setForeground(resourceMap.getColor("statusMessageLabel.foreground")); // NOI18N
        statusMessageLabel.setText(resourceMap.getString("statusMessageLabel.text")); // NOI18N
        statusMessageLabel.setName("statusMessageLabel"); // NOI18N
        getContentPane().add(statusMessageLabel);
        statusMessageLabel.setBounds(10, 150, 470, 14);

        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etsbackoffice/gui/resources/icons/banner.png"))); // NOI18N
        lblBanner.setMaximumSize(new java.awt.Dimension(500, 200));
        lblBanner.setName("lblBanner"); // NOI18N
        getContentPane().add(lblBanner);
        lblBanner.setBounds(0, 0, 503, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER || key == KeyEvent.VK_DOWN) {
            txtPWord.requestFocus();
        }
}//GEN-LAST:event_txtUserNameKeyPressed

    private void txtPWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPWordKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (txtUserName.getText().isEmpty() || txtPWord.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Enter UserName & Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
            } else {
                String userName = txtUserName.getText().trim();
                char[] p = txtPWord.getPassword();
                char[] newP = txtNewPassword.getPassword();
                String password = new String(p).trim();
                String newPassword = new String(newP).trim();

                if ((userName == null ? "" != null : !userName.equals("")) && (password == null ? "" != null : !password.equals(""))) {
                    new Thread(new threadLogin(userName, password, newPassword)).start();
                }
            }
        }
        if (key == KeyEvent.VK_UP) {
            txtUserName.requestFocus();
        }
}//GEN-LAST:event_txtPWordKeyPressed

    private void txtNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPasswordKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (txtUserName.getText().isEmpty() || txtPWord.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Enter UserName & Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
            } else {
                String userName = txtUserName.getText().trim();
                char[] p = txtPWord.getPassword();
                char[] newP = txtNewPassword.getPassword();
                String password = new String(p).trim();
                String newPassword = new String(newP).trim();

                if ((userName == null ? "" != null : !userName.equals("")) && (password == null ? "" != null : !password.equals(""))) {
                    new Thread(new threadLogin(userName, password, newPassword)).start();
                }
            }
        }
        if (key == KeyEvent.VK_UP) {
            txtUserName.requestFocus();
        }
}//GEN-LAST:event_txtNewPasswordKeyPressed
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        if (source == btnLogin) {
            String userName = txtUserName.getText().trim();
            char[] p = txtPWord.getPassword();
            char[] newP = txtNewPassword.getPassword();
            String password = new String(p).trim();
            String newPassword = new String(newP).trim();

            if ((userName == null ? "" != null : !userName.equals("")) && (password == null ? "" != null : !password.equals(""))) {
                new Thread(new threadLogin(userName, password, newPassword)).start();
            }else{
            JOptionPane.showMessageDialog(null, "Enter UserName & Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
            }
        } else if (source == btnCancel) {
            System.exit(0);
        }
    }
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
    
    public void run() {
    DlgLogin dialog = new DlgLogin(new javax.swing.JFrame());
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
    
    public void windowClosing(java.awt.event.WindowEvent e) {
    System.exit(0);
    }
    });
    dialog.setVisible(true);
    }
    });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private class threadLogin implements Runnable {

        private String userName = "";
        private String password = "";
        private String newPassword = "";

        public threadLogin(String userName, String password, String newPassword) {
            this.userName = userName;
            this.password = password;
            this.newPassword = newPassword;
        }

        public void run() {

            progressBar = new JProgressBar();
            progressBar.setIndeterminate(true); //Set value
            progressBar.repaint(); //Refresh graphics

            statusMessageLabel.setText("Configuring framework...");
            ETSBackofficeApp.getApplication().configureSpringContext();

            statusMessageLabel.setText("Checking credentials...");
            if (login(userName, password, newPassword)) {
                statusMessageLabel.setText("Loading Main Agent Profile...");
                MasterAgent mAgent = mAgentBo.loadMAgent();
                AuthenticationBo.setmAgent(mAgent);
                AppSettings appSettings = authenticationBo.loadAppSettings();

                if (appSettings == null) {
                    AuthenticationBo.setAppSettings(new AppSettings());
                } else {
                    AuthenticationBo.setAppSettings(appSettings);
                }

                statusMessageLabel.setText("Running services...");
                ETSBackofficeApp.getApplication().startFileReading();
                statusMessageLabel.setText("Initializing main frame...");
                ETSBackofficeApp.getApplication().showMainFrame();
                statusMessageLabel.setText("Done...");
                dispose();
            }
            progressBar.setIndeterminate(false);
            progressBar.repaint(); //Refresh graphics            
        }
    }
}
