package etsbackoffice.gui;

import etsbackoffice.domain.Ticket;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JDialog;
import org.jdesktop.application.Action;

/**
 *
 * @author Yusuf
 */
public class DlgTicket extends JDialog implements ActionListener {

    private boolean save;
    private Ticket ticket;// = (Ticket) ETSBackofficeApp.getApplication().ctx.getBean("ticket");

    /** Creates new form FrameTicket */
    public DlgTicket(java.awt.Frame parent) {
        super(parent, "Passenger & Ticket Details", true);
        initComponents();
        btnOk.addActionListener(this);
        btnCancel.addActionListener(this);
        CheckInput a = new CheckInput();
        CheckInput b = new CheckInput();
        CheckInput c = new CheckInput();
        CheckInput d = new CheckInput();
        CheckInput e = new CheckInput();
        CheckInput f = new CheckInput();
        CheckInput g = new CheckInput();

        c.setNegativeAccepted(true);

        txtBaseFare.setDocument(a);
        txtTax.setDocument(b);
        txtBspCom.setDocument(c);
        txtGrossFare.setDocument(d);
        txtDisc.setDocument(new CheckInput(CheckInput.FLOAT));
        txtAtol.setDocument(e);
        txtNumAirCode.setDocument(f);
        txtTktNo.setDocument(g);
    }

    @Action
    public void closeFrameTicketBox() {
        this.dispose();
    }

    public boolean showTicketDialog(Ticket ticket) {
        this.ticket = new Ticket();
        this.ticket = ticket;

        txtName.setText(this.ticket.getPaxSurName() + "/" + this.ticket.getPaxForeName());
        txtNumAirCode.setText(this.ticket.getNumericAirLineCode());
        txtTktNo.setText(this.ticket.getTicketNo());
        txtStatus.setText(this.ticket.getTktStatusString());
        datePicker.setDate(this.ticket.getDocIssuedate());
        txtBaseFare.setText(this.ticket.getBaseFare().toString());
        txtTax.setText(this.ticket.getTax().toString());
        txtTotalFare.setText(this.ticket.getBaseFare().add(this.ticket.getTax()).toString());
        txtBspCom.setText(this.ticket.getBspCom().toString());
        txtNetFare.setText(this.ticket.getNetFare().toString());
        txtBFVendor.setText(this.ticket.getBaseFareVendor().toString());
        txtTaxVendor.setText(this.ticket.getTaxVendor().toString());
        txtTotalVendor.setText(this.ticket.getBaseFareVendor().add(this.ticket.getTaxVendor()).toString());

        txtGrossFare.setText(this.ticket.getGrossFare().toString());
        txtDisc.setText(this.ticket.getDiscount().toString());
        txtAtol.setText(this.ticket.getAtolChg().toString());
        txtNettToPay.setText(this.ticket.getNetPayble().toString());
        lblProfitLoss.setText(this.ticket.getTktdRevenue().toString());

        /*if (!this.ticket.getAccountingDocumentLine().isEmpty()) {
        txtBaseFare.setEditable(false);
        txtTax.setEditable(false);
        txtGrossFare.setEditable(false);
        txtDisc.setEditable(false);
        txtAtol.setEditable(false);
        }*/

        save = false;
        setLocationRelativeTo(this);
        setVisible(true);

        if (save) {
            ticket = this.ticket;
        }
        return save;
    }

    private void populateTotalFare() {
        txtTotalFare.setText(this.ticket.getBaseFare().add(this.ticket.getTax()).toString());
        txtNetFare.setText(this.ticket.getNetFare().toString());
    }

    private void populateNettToPay() {
        txtNettToPay.setText(this.ticket.getNetPayble().toString());
    }

    private void populateProfitLoss() {
        lblProfitLoss.setText(this.ticket.getTktdRevenue().toString());
    }

    public void actionPerformed(ActionEvent evt) {
        Object source = evt.getSource();
        if (source == btnOk) {
            save = true;
            setVisible(false);

        } else {
            dispose();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBaseFare = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblTotalFare = new javax.swing.JLabel();
        lblBspCom = new javax.swing.JLabel();
        lblGrossFare = new javax.swing.JLabel();
        lblDisc = new javax.swing.JLabel();
        lblAtol = new javax.swing.JLabel();
        lblNetToPay = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtTktNo = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtBaseFare = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        txtTotalFare = new javax.swing.JTextField();
        txtBspCom = new javax.swing.JTextField();
        txtGrossFare = new javax.swing.JTextField();
        txtDisc = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtAtol = new javax.swing.JTextField();
        txtNettToPay = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        lblProfitLoss = new javax.swing.JLabel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        lblGFMessage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBFVendor = new javax.swing.JTextField();
        txtTaxVendor = new javax.swing.JTextField();
        txtTotalVendor = new javax.swing.JTextField();
        txtNumAirCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNetFare = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(etsbackoffice.ETSBackofficeApp.class).getContext().getResourceMap(DlgTicket.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(150, 20));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(jLabel4, gridBagConstraints);

        lblBaseFare.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblBaseFare.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBaseFare.setText(resourceMap.getString("lblBaseFare.text")); // NOI18N
        lblBaseFare.setName("lblBaseFare"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblBaseFare, gridBagConstraints);

        lblTax.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblTax.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTax.setText(resourceMap.getString("lblTax.text")); // NOI18N
        lblTax.setName("lblTax"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblTax, gridBagConstraints);

        lblTotalFare.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblTotalFare.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTotalFare.setText(resourceMap.getString("lblTotalFare.text")); // NOI18N
        lblTotalFare.setName("lblTotalFare"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblTotalFare, gridBagConstraints);

        lblBspCom.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblBspCom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBspCom.setText(resourceMap.getString("lblBspCom.text")); // NOI18N
        lblBspCom.setName("lblBspCom"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblBspCom, gridBagConstraints);

        lblGrossFare.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblGrossFare.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGrossFare.setText(resourceMap.getString("lblGrossFare.text")); // NOI18N
        lblGrossFare.setName("lblGrossFare"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblGrossFare, gridBagConstraints);

        lblDisc.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblDisc.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDisc.setText(resourceMap.getString("lblDisc.text")); // NOI18N
        lblDisc.setName("lblDisc"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblDisc, gridBagConstraints);

        lblAtol.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblAtol.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAtol.setText(resourceMap.getString("lblAtol.text")); // NOI18N
        lblAtol.setName("lblAtol"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblAtol, gridBagConstraints);

        lblNetToPay.setFont(resourceMap.getFont("lblBspCom.font")); // NOI18N
        lblNetToPay.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNetToPay.setText(resourceMap.getString("lblNetToPay.text")); // NOI18N
        lblNetToPay.setName("lblNetToPay"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 2);
        getContentPane().add(lblNetToPay, gridBagConstraints);

        jLabel13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel13.setForeground(resourceMap.getColor("jLabel13.foreground")); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel13, gridBagConstraints);

        txtName.setEditable(false);
        txtName.setFont(resourceMap.getFont("txtName.font")); // NOI18N
        txtName.setText(resourceMap.getString("txtName.text")); // NOI18N
        txtName.setName("txtName"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtName, gridBagConstraints);

        txtTktNo.setFont(resourceMap.getFont("txtTktNo.font")); // NOI18N
        txtTktNo.setText(resourceMap.getString("txtTktNo.text")); // NOI18N
        txtTktNo.setName("txtTktNo"); // NOI18N
        txtTktNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTktNoKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtTktNo, gridBagConstraints);

        txtStatus.setEditable(false);
        txtStatus.setFont(resourceMap.getFont("txtStatus.font")); // NOI18N
        txtStatus.setText(resourceMap.getString("txtStatus.text")); // NOI18N
        txtStatus.setMinimumSize(new java.awt.Dimension(150, 20));
        txtStatus.setName("txtStatus"); // NOI18N
        txtStatus.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtStatus, gridBagConstraints);

        txtBaseFare.setFont(resourceMap.getFont("txtDisc.font")); // NOI18N
        txtBaseFare.setText(resourceMap.getString("txtBaseFare.text")); // NOI18N
        txtBaseFare.setMinimumSize(new java.awt.Dimension(150, 20));
        txtBaseFare.setName("txtBaseFare"); // NOI18N
        txtBaseFare.setPreferredSize(new java.awt.Dimension(150, 20));
        txtBaseFare.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBaseFareFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBaseFareFocusLost(evt);
            }
        });
        txtBaseFare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBaseFareKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtBaseFare, gridBagConstraints);

        txtTax.setFont(resourceMap.getFont("txtDisc.font")); // NOI18N
        txtTax.setText(resourceMap.getString("txtTax.text")); // NOI18N
        txtTax.setMinimumSize(new java.awt.Dimension(150, 20));
        txtTax.setName("txtTax"); // NOI18N
        txtTax.setPreferredSize(new java.awt.Dimension(150, 20));
        txtTax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTaxFocusLost(evt);
            }
        });
        txtTax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTaxKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtTax, gridBagConstraints);

        txtTotalFare.setEditable(false);
        txtTotalFare.setFont(resourceMap.getFont("txtTotalFare.font")); // NOI18N
        txtTotalFare.setForeground(resourceMap.getColor("txtTotalFare.foreground")); // NOI18N
        txtTotalFare.setMinimumSize(new java.awt.Dimension(150, 20));
        txtTotalFare.setName("txtTotalFare"); // NOI18N
        txtTotalFare.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtTotalFare, gridBagConstraints);

        txtBspCom.setFont(resourceMap.getFont("txtDisc.font")); // NOI18N
        txtBspCom.setMinimumSize(new java.awt.Dimension(150, 20));
        txtBspCom.setName("txtBspCom"); // NOI18N
        txtBspCom.setPreferredSize(new java.awt.Dimension(150, 20));
        txtBspCom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBspComFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBspComFocusLost(evt);
            }
        });
        txtBspCom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBspComKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtBspCom, gridBagConstraints);

        txtGrossFare.setBackground(resourceMap.getColor("txtGrossFare.background")); // NOI18N
        txtGrossFare.setFont(resourceMap.getFont("txtDisc.font")); // NOI18N
        txtGrossFare.setMinimumSize(new java.awt.Dimension(150, 20));
        txtGrossFare.setName("txtGrossFare"); // NOI18N
        txtGrossFare.setPreferredSize(new java.awt.Dimension(150, 20));
        txtGrossFare.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGrossFareFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGrossFareFocusLost(evt);
            }
        });
        txtGrossFare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrossFareKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtGrossFare, gridBagConstraints);

        txtDisc.setFont(resourceMap.getFont("txtDisc.font")); // NOI18N
        txtDisc.setMinimumSize(new java.awt.Dimension(150, 20));
        txtDisc.setName("txtDisc"); // NOI18N
        txtDisc.setPreferredSize(new java.awt.Dimension(150, 20));
        txtDisc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiscFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiscFocusLost(evt);
            }
        });
        txtDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiscKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtDisc, gridBagConstraints);

        jSeparator3.setName("jSeparator3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weighty = 4.0;
        getContentPane().add(jSeparator3, gridBagConstraints);

        txtAtol.setFont(resourceMap.getFont("txtDisc.font")); // NOI18N
        txtAtol.setMinimumSize(new java.awt.Dimension(150, 20));
        txtAtol.setName("txtAtol"); // NOI18N
        txtAtol.setPreferredSize(new java.awt.Dimension(150, 20));
        txtAtol.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAtolFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAtolFocusLost(evt);
            }
        });
        txtAtol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAtolKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtAtol, gridBagConstraints);

        txtNettToPay.setEditable(false);
        txtNettToPay.setFont(resourceMap.getFont("txtNettToPay.font")); // NOI18N
        txtNettToPay.setForeground(resourceMap.getColor("txtNettToPay.foreground")); // NOI18N
        txtNettToPay.setText(resourceMap.getString("txtNettToPay.text")); // NOI18N
        txtNettToPay.setMinimumSize(new java.awt.Dimension(150, 20));
        txtNettToPay.setName("txtNettToPay"); // NOI18N
        txtNettToPay.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtNettToPay, gridBagConstraints);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(etsbackoffice.ETSBackofficeApp.class).getContext().getActionMap(DlgTicket.class, this);
        btnCancel.setAction(actionMap.get("closeFrameTicketBox")); // NOI18N
        btnCancel.setFont(resourceMap.getFont("btnCancel.font")); // NOI18N
        btnCancel.setIcon(resourceMap.getIcon("btnCancel.icon")); // NOI18N
        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(btnCancel, gridBagConstraints);

        btnOk.setFont(resourceMap.getFont("btnOk.font")); // NOI18N
        btnOk.setIcon(resourceMap.getIcon("btnOk.icon")); // NOI18N
        btnOk.setText(resourceMap.getString("btnOk.text")); // NOI18N
        btnOk.setName("btnOk"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 6, 2);
        getContentPane().add(btnOk, gridBagConstraints);

        jSeparator1.setName("jSeparator1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        getContentPane().add(jSeparator1, gridBagConstraints);

        jSeparator2.setName("jSeparator2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 8, 0);
        getContentPane().add(jSeparator2, gridBagConstraints);

        jLabel14.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel14.setForeground(resourceMap.getColor("jLabel14.foreground")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 6, 2, 0);
        getContentPane().add(jLabel14, gridBagConstraints);

        lblProfitLoss.setFont(resourceMap.getFont("lblProfitLoss.font")); // NOI18N
        lblProfitLoss.setForeground(resourceMap.getColor("lblProfitLoss.foreground")); // NOI18N
        lblProfitLoss.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProfitLoss.setText(resourceMap.getString("lblProfitLoss.text")); // NOI18N
        lblProfitLoss.setName("lblProfitLoss"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(lblProfitLoss, gridBagConstraints);

        datePicker.setFont(resourceMap.getFont("datePicker.font")); // NOI18N
        datePicker.setName("datePicker"); // NOI18N
        datePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePickerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(datePicker, gridBagConstraints);

        lblGFMessage.setFont(resourceMap.getFont("lblGFMessage.font")); // NOI18N
        lblGFMessage.setForeground(resourceMap.getColor("lblGFMessage.foreground")); // NOI18N
        lblGFMessage.setText(resourceMap.getString("lblGFMessage.text")); // NOI18N
        lblGFMessage.setName("lblGFMessage"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        getContentPane().add(lblGFMessage, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel6, gridBagConstraints);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jLabel7, gridBagConstraints);

        txtBFVendor.setEditable(false);
        txtBFVendor.setFont(resourceMap.getFont("txtTotalVendor.font")); // NOI18N
        txtBFVendor.setText(resourceMap.getString("txtBFVendor.text")); // NOI18N
        txtBFVendor.setName("txtBFVendor"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtBFVendor, gridBagConstraints);

        txtTaxVendor.setEditable(false);
        txtTaxVendor.setFont(resourceMap.getFont("txtTotalVendor.font")); // NOI18N
        txtTaxVendor.setText(resourceMap.getString("txtTaxVendor.text")); // NOI18N
        txtTaxVendor.setName("txtTaxVendor"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtTaxVendor, gridBagConstraints);

        txtTotalVendor.setEditable(false);
        txtTotalVendor.setFont(resourceMap.getFont("txtTotalVendor.font")); // NOI18N
        txtTotalVendor.setText(resourceMap.getString("txtTotalVendor.text")); // NOI18N
        txtTotalVendor.setName("txtTotalVendor"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtTotalVendor, gridBagConstraints);

        txtNumAirCode.setFont(resourceMap.getFont("txtNumAirCode.font")); // NOI18N
        txtNumAirCode.setText(resourceMap.getString("txtNumAirCode.text")); // NOI18N
        txtNumAirCode.setMinimumSize(new java.awt.Dimension(150, 20));
        txtNumAirCode.setName("txtNumAirCode"); // NOI18N
        txtNumAirCode.setPreferredSize(new java.awt.Dimension(150, 20));
        txtNumAirCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumAirCodeKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtNumAirCode, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 0, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        getContentPane().add(jLabel9, gridBagConstraints);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        getContentPane().add(jLabel10, gridBagConstraints);

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(jLabel11, gridBagConstraints);

        txtNetFare.setEditable(false);
        txtNetFare.setFont(resourceMap.getFont("txtNetFare.font")); // NOI18N
        txtNetFare.setText(resourceMap.getString("txtNetFare.text")); // NOI18N
        txtNetFare.setName("txtNetFare"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(txtNetFare, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBaseFareKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBaseFareKeyReleased
        String text = txtBaseFare.getText();
        BigDecimal bf = new BigDecimal("0.00");

        if (!text.isEmpty()) {
            bf = new BigDecimal(text).setScale(2, RoundingMode.DOWN);
        }
        this.ticket.setBaseFare(bf);
        populateTotalFare();
        populateProfitLoss();
    }//GEN-LAST:event_txtBaseFareKeyReleased

    private void txtTaxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaxKeyReleased
        String text = txtTax.getText();
        BigDecimal tax = new BigDecimal("0.00");

        if (!text.isEmpty()) {
            tax = new BigDecimal(text);
        }
        this.ticket.setTax(tax);
        populateTotalFare();
        populateProfitLoss();
    }//GEN-LAST:event_txtTaxKeyReleased

    private void txtGrossFareKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrossFareKeyReleased
        int key = evt.getKeyCode();
        String text = txtGrossFare.getText();

        BigDecimal gf = new BigDecimal("0.00");

        if (!text.isEmpty() && key != KeyEvent.VK_ENTER) {
            gf = new BigDecimal(text);

            if (this.ticket.getGrossFare().compareTo(this.ticket.getBaseFare().add(this.ticket.getTax())) == -1) {
                lblGFMessage.setText("Gross fare is less then system fare");
            } else {
                lblGFMessage.setText("");
            }
        } else if (key == KeyEvent.VK_ENTER || key == KeyEvent.VK_DOWN) {
            txtDisc.requestFocus();
        } else if (key == KeyEvent.VK_UP) {
            txtBspCom.requestFocus();
        }
        this.ticket.setGrossFare(gf);
        populateNettToPay();
        populateProfitLoss();
    }//GEN-LAST:event_txtGrossFareKeyReleased

    private void txtDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscKeyReleased
        int key = evt.getKeyCode();
        String text = txtDisc.getText().replaceAll("[^.0-9]", "");
        BigDecimal disc = new BigDecimal("0.00");

        if (!text.isEmpty() && key != KeyEvent.VK_ENTER) {
            disc = new BigDecimal(text).negate();
        } else if (key == KeyEvent.VK_ENTER || key == KeyEvent.VK_DOWN) {
            txtAtol.requestFocus();
        } else if (key == KeyEvent.VK_UP) {
            txtGrossFare.requestFocus();
        }
        this.ticket.setDiscount(disc);
        populateNettToPay();
        populateProfitLoss();
    }//GEN-LAST:event_txtDiscKeyReleased

    private void txtAtolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAtolKeyReleased
        int key = evt.getKeyCode();
        String text = txtAtol.getText();
        BigDecimal atol = new BigDecimal("0.00");

        if (!text.isEmpty() && key != KeyEvent.VK_ENTER) {
            atol = new BigDecimal(text);
        } else if (key == KeyEvent.VK_ENTER || key == KeyEvent.VK_DOWN) {
            //txtAtol.requestFocus();
        } else if (key == KeyEvent.VK_UP) {
            txtDisc.requestFocus();
        }
        this.ticket.setAtolChg(atol);
        populateNettToPay();
    }//GEN-LAST:event_txtAtolKeyReleased

    private void txtBspComKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBspComKeyReleased
        String text = txtBspCom.getText().replaceAll("[^.0-9]", "");
        BigDecimal bspCom = new BigDecimal("0.00");

        if (!text.isEmpty()) {
            bspCom = new BigDecimal(text).negate();
        }
        this.ticket.setBspCom(bspCom);
        populateProfitLoss();
        populateTotalFare();
    }//GEN-LAST:event_txtBspComKeyReleased

    private void txtGrossFareFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGrossFareFocusGained
        txtGrossFare.selectAll();
    }//GEN-LAST:event_txtGrossFareFocusGained

    private void txtGrossFareFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGrossFareFocusLost
        txtGrossFare.setText(this.ticket.getGrossFare().toString());
    }//GEN-LAST:event_txtGrossFareFocusLost

    private void txtDiscFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscFocusGained
        txtDisc.selectAll();
    }//GEN-LAST:event_txtDiscFocusGained

    private void txtDiscFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscFocusLost
        txtDisc.setText(this.ticket.getDiscount().toString());
    }//GEN-LAST:event_txtDiscFocusLost

    private void txtAtolFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAtolFocusGained
        txtAtol.selectAll();
    }//GEN-LAST:event_txtAtolFocusGained

    private void txtAtolFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAtolFocusLost
        txtAtol.setText(this.ticket.getAtolChg().toString());
    }//GEN-LAST:event_txtAtolFocusLost

    private void txtBspComFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBspComFocusGained
        txtBspCom.selectAll();
    }//GEN-LAST:event_txtBspComFocusGained

    private void txtBspComFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBspComFocusLost
        txtBspCom.setText(this.ticket.getBspCom().toString());
    }//GEN-LAST:event_txtBspComFocusLost

    private void txtTaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTaxFocusLost
        txtTax.setText(this.ticket.getTax().toString());
    }//GEN-LAST:event_txtTaxFocusLost

    private void txtTaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTaxFocusGained
        txtTax.selectAll();
    }//GEN-LAST:event_txtTaxFocusGained

    private void txtBaseFareFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBaseFareFocusGained
        txtBaseFare.selectAll();
    }//GEN-LAST:event_txtBaseFareFocusGained

    private void txtBaseFareFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBaseFareFocusLost
        txtBaseFare.setText(this.ticket.getBaseFare().toString());
    }//GEN-LAST:event_txtBaseFareFocusLost

    private void txtNumAirCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumAirCodeKeyReleased
        this.ticket.setNumericAirLineCode(txtNumAirCode.getText());
    }//GEN-LAST:event_txtNumAirCodeKeyReleased

    private void txtTktNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTktNoKeyReleased
        this.ticket.setTicketNo(txtTktNo.getText());
    }//GEN-LAST:event_txtTktNoKeyReleased

    private void datePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePickerActionPerformed
        this.ticket.setDocIssuedate(datePicker.getDate());
    }//GEN-LAST:event_datePickerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAtol;
    private javax.swing.JLabel lblBaseFare;
    private javax.swing.JLabel lblBspCom;
    private javax.swing.JLabel lblDisc;
    private javax.swing.JLabel lblGFMessage;
    private javax.swing.JLabel lblGrossFare;
    private javax.swing.JLabel lblNetToPay;
    private javax.swing.JLabel lblProfitLoss;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotalFare;
    private javax.swing.JTextField txtAtol;
    private javax.swing.JTextField txtBFVendor;
    private javax.swing.JTextField txtBaseFare;
    private javax.swing.JTextField txtBspCom;
    private javax.swing.JTextField txtDisc;
    private javax.swing.JTextField txtGrossFare;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNetFare;
    private javax.swing.JTextField txtNettToPay;
    private javax.swing.JTextField txtNumAirCode;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTax;
    private javax.swing.JTextField txtTaxVendor;
    private javax.swing.JTextField txtTktNo;
    private javax.swing.JTextField txtTotalFare;
    private javax.swing.JTextField txtTotalVendor;
    // End of variables declaration//GEN-END:variables
}
