package etsbackoffice.gui;

import etsbackoffice.ETSBackofficeApp;
import etsbackoffice.businesslogic.AuthenticationBo;
import etsbackoffice.businesslogic.MAgentBo;
import etsbackoffice.businesslogic.UserBo;
import etsbackoffice.domain.AppSettings;
import etsbackoffice.domain.MasterAgent;
import etsbackoffice.domain.User;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

public class FrameLogin extends javax.swing.JFrame {

    Image img;
    AuthenticationBo authenticationBo;//  = (AuthenticationBo) ETSBackofficeApp.getApplication().ctx.getBean("authenticationBo");    
    MAgentBo mAgentBo;
    User user;
    AppSettings appSettings;

    public FrameLogin() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setLocation(screenWidth / 2 - 200, screenHeight / 2 - 200);
        initComponents();
    }

    public void showLoginForm() {
        setVisible(true);
    }

    public boolean login() {
 String userName = txtUserName.getText();
        char[] p = txtPWord.getPassword();
        char[] newP = txtNewPassword.getPassword();
        boolean authenticate = false;
        try{
        authenticationBo = (AuthenticationBo) ETSBackofficeApp.getApplication().ctx.getBean("authenticationBo");
        mAgentBo = (MAgentBo) ETSBackofficeApp.getApplication().ctx.getBean("mAgentBo");
        UserBo userBo = (UserBo) ETSBackofficeApp.getApplication().ctx.getBean("userBo");        
        
        
        String password = new String(p);
        String newPassword = new String(newP);
        password.trim();
        newPassword.trim();        

        if ((userName == null ? "" != null : !userName.equals("")) && (password == null ? "" != null : !password.equals(""))) {
            user = authenticationBo.checkLoginDetails(userName, password);
            if (user == null) {
                authenticate = false;
            } else {
                authenticate = true;
            }
        }

        //return authenticate;
        if (authenticate) {
            if (!newPassword.isEmpty()) {
                user.setPassword(newPassword);
                userBo.setUser(user);
                userBo.saveUser();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Wrong UserName or Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
        }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e, "Login Exception", JOptionPane.WARNING_MESSAGE);
        }
        return authenticate;

    }

 /*   @Action
    public void actionLoginPerformed() {

        if (txtUserName.getText().isEmpty() || txtPWord.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Enter UserName & Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
        } else {
            login();
        }
    }*/

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        statusMessageLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtPWord = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ETSBackoffice : Login");
        setMinimumSize(new java.awt.Dimension(500, 200));
        setResizable(false);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(progressBar);
        progressBar.setBounds(326, 180, 170, 19);

        statusMessageLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        statusMessageLabel.setForeground(new java.awt.Color(255, 255, 0));
        statusMessageLabel.setText("Status...");
        getContentPane().add(statusMessageLabel);
        statusMessageLabel.setBounds(10, 150, 460, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 14));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 80, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 14));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 60, 70, 14);

        txtUserName.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(290, 30, 180, 20);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(etsbackoffice.ETSBackofficeApp.class).getContext().getActionMap(FrameLogin.class, this);
        btnLogin.setAction(actionMap.get("actionLoginPerformed")); // NOI18N
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(etsbackoffice.ETSBackofficeApp.class).getContext().getResourceMap(FrameLogin.class);
        btnLogin.setText(resourceMap.getString("btnLogin.text")); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(290, 120, 85, 25);

        txtPWord.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtPWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPWordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPWord);
        txtPWord.setBounds(290, 60, 180, 20);

        txtNewPassword.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtNewPassword);
        txtNewPassword.setBounds(290, 90, 180, 20);

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(390, 120, 85, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NewPassword");
        jLabel4.setPreferredSize(new java.awt.Dimension(60, 14));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 90, 80, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/etsbackoffice/gui/resources/icons/banner.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 200));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 503, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        if (txtUserName.getText().isEmpty() || txtPWord.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null, "Enter UserName & Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
        } else {
           new Thread(new threadLogin()).start();
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER || key == KeyEvent.VK_DOWN) {
            txtPWord.requestFocus();
        }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void txtPWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPWordKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (txtUserName.getText().isEmpty() || txtPWord.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Enter UserName & Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
            } else {
                new Thread(new threadLogin()).start();
            }
        }
        if (key == KeyEvent.VK_UP) {
            txtUserName.requestFocus();
        }
    }//GEN-LAST:event_txtPWordKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ESCAPE) {
            System.exit(1);
        }
    }//GEN-LAST:event_formKeyPressed

    private void txtNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPasswordKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            if (txtUserName.getText().isEmpty() || txtPWord.getPassword().length == 0) {
                JOptionPane.showMessageDialog(null, "Enter UserName & Password...", "ETSBackoffice login....", JOptionPane.WARNING_MESSAGE);
            } else {
                new Thread(new threadLogin()).start();
            }
        }
        if (key == KeyEvent.VK_UP) {
            txtUserName.requestFocus();
        }
    }//GEN-LAST:event_txtNewPasswordKeyPressed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrameLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtPWord;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
    
    private class threadLogin implements Runnable {        

        public threadLogin() {
            
        }

        public void run() {

            progressBar = new JProgressBar();
            progressBar.setIndeterminate(true); //Set value
            progressBar.repaint(); //Refresh graphics

            statusMessageLabel.setText("Configuring framework...");
            ETSBackofficeApp.getApplication().configureSpringContext();

            statusMessageLabel.setText("Checking credentials...");
            if(login()){
            statusMessageLabel.setText("Loading Main Agent Profile...");
            MasterAgent mAgent = mAgentBo.loadMAgent();
            AuthenticationBo.setmAgent(mAgent);
            AppSettings appSettings = authenticationBo.loadAppSettings();
            
            if(appSettings == null){
            AuthenticationBo.setAppSettings(new AppSettings());
            }else{
            AuthenticationBo.setAppSettings(appSettings);
            }
            
            statusMessageLabel.setText("Running services...");
            ETSBackofficeApp.getApplication().startFileReading();
            statusMessageLabel.setText("Initializing main frame...");
            ETSBackofficeApp.getApplication().showMainFrame();
            statusMessageLabel.setText("Done...");
            dispose();
            }           
            progressBar.setIndeterminate(false);
            progressBar.repaint(); //Refresh graphics            
        }
    }

}
