package com.ets.fe.a_main;

import com.ets.fe.accounts.gui.payment.*;
import com.amadeus.reader.EventSource;
import com.amadeus.reader.ResponseHandler;
import com.ets.fe.APIConfig;
import com.ets.fe.Application;
import com.ets.fe.accounts.gui.report.*;
import com.ets.fe.acdoc.gui.report.*;
import com.ets.fe.acdoc_o.gui.OtherInvoiceDlg;
import com.ets.fe.acdoc_o.gui.OtherInvoiceReportingFrame;
import com.ets.fe.accounts.gui.payment.OtherSalesBatchPayment;
import com.ets.fe.acdoc_o.gui.OtherSalesBatchPaymentReport;
import com.ets.fe.app.model.AppSettings;
import com.ets.fe.client.gui.*;
import com.ets.fe.client.model.*;
import com.ets.fe.os.gui.OtherServiceFrame;
import com.ets.fe.pnr.gui.*;
import com.ets.fe.settings.gui.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Yusuf
 */
public class Main extends JFrame implements PropertyChangeListener {

    private static boolean loginSuccess = false;
    private List<JInternalFrame> internalFrames = new ArrayList<>();
    //private Application appSettings;
    private APIConfig aPIConfig;
    private String taskType = "";

    public Main() {
        initComponents();
        aPIConfig = new APIConfig();
        Application.loadSettings();
        int inset = 50;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(inset, inset,
                screenSize.width - inset * 2,
                screenSize.height - inset * 2);

        callDashBoard();
        startFileReading();

        //Make dragging a little faster but perhaps uglier.
        desktopPane.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
        
    }
    
    private void callDashBoard() {
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                DashBoardFrame frame = new DashBoardFrame();
                frame.setVisible(true);
                desktopPane.add(frame);
                try {
                    frame.setMaximum(true);
                    frame.setSelected(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }

                internalFrames.add(frame);
            }
        });
    }

    public void startFileReading() {
        ResponseHandler respHandler = new ResponseHandler();
        EventSource evSrc = new EventSource();
        evSrc.addObserver(respHandler);
        Thread thread = new Thread(evSrc);
        thread.start();
        System.out.println("Observer started...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnNewCustomer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuAppSettings = new javax.swing.JMenuItem();
        menuMainAgent = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPnrHistory = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuDueSalesInvoice = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuBatchTransaction = new javax.swing.JMenuItem();
        menuBatchTransRpt = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuClientAccounts = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuPReporting = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu3rdPartyBillPayment = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuVendorAccounts = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuDueOSalesInvoice = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));

        btnNewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newClient24.png"))); // NOI18N
        btnNewCustomer.setFocusable(false);
        btnNewCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewCustomer.setPreferredSize(new java.awt.Dimension(50, 24));
        btnNewCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewCustomer);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Settings");

        jMenuItem4.setText("Air Lines");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        menuAppSettings.setText("Application Settings");
        menuAppSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAppSettingsActionPerformed(evt);
            }
        });
        jMenu4.add(menuAppSettings);

        menuMainAgent.setText("Company Profile");
        menuMainAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainAgentActionPerformed(evt);
            }
        });
        jMenu4.add(menuMainAgent);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Client");

        jMenuItem1.setText("Customer Management");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem5.setText("Agent Management");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("Pnr");

        menuPnrHistory.setText("Pnr History");
        menuPnrHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPnrHistoryActionPerformed(evt);
            }
        });
        jMenu3.add(menuPnrHistory);

        jMenuItem2.setText("Ticket History");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Segment History");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Sales");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        menuDueSalesInvoice.setText("Sales Invoice: Report");
        menuDueSalesInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDueSalesInvoiceActionPerformed(evt);
            }
        });
        jMenu6.add(menuDueSalesInvoice);
        jMenu6.add(jSeparator1);

        menuBatchTransaction.setText("Batch Transaction");
        menuBatchTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBatchTransactionActionPerformed(evt);
            }
        });
        jMenu6.add(menuBatchTransaction);

        menuBatchTransRpt.setText("History: Batch Transaction");
        menuBatchTransRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBatchTransRptActionPerformed(evt);
            }
        });
        jMenu6.add(menuBatchTransRpt);
        jMenu6.add(jSeparator4);

        menuClientAccounts.setText("History: Client Account");
        menuClientAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientAccountsActionPerformed(evt);
            }
        });
        jMenu6.add(menuClientAccounts);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Purchase");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        menuPReporting.setText("Purchase Invoice: Report");
        menuPReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPReportingActionPerformed(evt);
            }
        });
        jMenu7.add(menuPReporting);
        jMenu7.add(jSeparator2);

        menu3rdPartyBillPayment.setText("Bill Payment: 3rd Party");
        menu3rdPartyBillPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3rdPartyBillPaymentActionPerformed(evt);
            }
        });
        jMenu7.add(menu3rdPartyBillPayment);

        jMenuItem7.setText("History: Bill Payment");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);
        jMenu7.add(jSeparator3);

        menuVendorAccounts.setText("History: Vendor Account");
        menuVendorAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendorAccountsActionPerformed(evt);
            }
        });
        jMenu7.add(menuVendorAccounts);

        jMenuBar1.add(jMenu7);

        jMenu2.setText("Services");

        jMenuItem6.setText("Service Manager");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Other Invoicing");

        jMenuItem8.setText("New Invoice");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);
        jMenu8.add(jSeparator5);

        menuDueOSalesInvoice.setText("Other Invoice: Report");
        menuDueOSalesInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDueOSalesInvoiceActionPerformed(evt);
            }
        });
        jMenu8.add(menuDueOSalesInvoice);

        jMenuItem9.setText("Batch Transaction");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("History: Batch Transaction");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);
        jMenu8.add(jSeparator6);

        jMenuItem11.setText("History: Client Account");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPnrHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPnrHistoryActionPerformed
        PnrHistoryFrame history = new PnrHistoryFrame();
        desktopPane.add(history);
        try {
            history.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        history.setVisible(true);
    }//GEN-LAST:event_menuPnrHistoryActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                TktSaleReportFrame frame = new TktSaleReportFrame();
                desktopPane.add(frame);
                try {
                    frame.setSelected(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
                frame.setVisible(true);
                internalFrames.add(frame);
            }
        });

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SegmentReportFrame frame = new SegmentReportFrame();
        desktopPane.add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        CustomerDlg customerDlg = new CustomerDlg(this);
        customerDlg.setTitle("New Customer");
        Customer newCustomer = new Customer();
        if (customerDlg.showDialog(newCustomer)) {
            CustomerTask task = new CustomerTask(newCustomer);
            task.execute();
        }
    }//GEN-LAST:event_btnNewCustomerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CustomerFrame frame = new CustomerFrame(desktopPane);
        desktopPane.add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        AgentFrame frame = new AgentFrame(desktopPane);
        desktopPane.add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        OtherServiceFrame frame = new OtherServiceFrame(desktopPane);
        desktopPane.add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuAppSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAppSettingsActionPerformed
        SettingsDlg dlg = new SettingsDlg(this);
        AppSettings settings = Application.getAppSettings();
        if (settings == null) {
            settings = new AppSettings();
        }
        if (dlg.showDialog(settings)) {
            SettingsTask task = new SettingsTask(settings);
            task.addPropertyChangeListener(this);
            task.execute();
            taskType = "SETTINGS";
        }
    }//GEN-LAST:event_menuAppSettingsActionPerformed

    private void menuMainAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainAgentActionPerformed
        MainAgentDlg dlg = new MainAgentDlg(this);
        MainAgent agent = Application.getMainAgent();
        if (agent == null) {
            agent = new MainAgent();
        }
        if (dlg.showDialog(agent)) {
            MainAgentTask task = new MainAgentTask(agent);
            task.addPropertyChangeListener(this);
            task.execute();
            taskType = "SETTINGS";
        }
    }//GEN-LAST:event_menuMainAgentActionPerformed

    private void menuDueSalesInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDueSalesInvoiceActionPerformed
        frameAction(new TSalesInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuDueSalesInvoiceActionPerformed

    private void menuPReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPReportingActionPerformed
        frameAction(new TPurchaseInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuPReportingActionPerformed

    private void menuBatchTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBatchTransactionActionPerformed
        frameAction(new TSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_menuBatchTransactionActionPerformed

    private void menu3rdPartyBillPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3rdPartyBillPaymentActionPerformed
        frameAction(new TPurchaseBatchPayment(desktopPane));
    }//GEN-LAST:event_menu3rdPartyBillPaymentActionPerformed

    private void menuBatchTransRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBatchTransRptActionPerformed
        frameAction(new TSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_menuBatchTransRptActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frameAction(new TPurchaseBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuClientAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientAccountsActionPerformed
        frameAction(new TSalesAccountsFrame(desktopPane));
    }//GEN-LAST:event_menuClientAccountsActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed

    }//GEN-LAST:event_jMenu7ActionPerformed

    private void menuVendorAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendorAccountsActionPerformed
        frameAction(new TPurchaseAccountsFrame(desktopPane));
    }//GEN-LAST:event_menuVendorAccountsActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        OtherInvoiceDlg dlg = new OtherInvoiceDlg(this);
        dlg.showDialog(null);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuDueOSalesInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDueOSalesInvoiceActionPerformed
        frameAction(new OtherInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuDueOSalesInvoiceActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        frameAction(new OtherSalesAccountsFrame(desktopPane));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        frameAction(new OtherSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        frameAction(new OtherSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void frameAction(JInternalFrame frame) {
        desktopPane.add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        frame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getFullName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    if(Application.getLoggedOnUser()!=null){
                        System.out.println("Accessed>>>>>");
                     new Main().setVisible(true);
                    }
                }
            });        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem menu3rdPartyBillPayment;
    private javax.swing.JMenuItem menuAppSettings;
    private javax.swing.JMenuItem menuBatchTransRpt;
    private javax.swing.JMenuItem menuBatchTransaction;
    private javax.swing.JMenuItem menuClientAccounts;
    private javax.swing.JMenuItem menuDueOSalesInvoice;
    private javax.swing.JMenuItem menuDueSalesInvoice;
    private javax.swing.JMenuItem menuMainAgent;
    private javax.swing.JMenuItem menuPReporting;
    private javax.swing.JMenuItem menuPnrHistory;
    private javax.swing.JMenuItem menuVendorAccounts;
    // End of variables declaration//GEN-END:variables
@Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress".equals(evt.getPropertyName())) {
            int progress = (Integer) evt.getNewValue();
            //progressBar.setValue(progress);
            if (progress == 100) {
                if ("SETTINGS".equals(taskType)) {
                    Application.loadSettings();
                }
            }
        }
    }

}
