package com.ets.fe.a_main;

import com.ets.fe.client.task.AgentTask;
import com.ets.fe.client.task.CustomerTask;
import com.ets.fe.tools.gui.TicketingDiscrepancyFrame;
import com.ets.fe.accounts.gui.revenue.TicketSaleReportFrame;
import com.ets.fe.accounts.gui.payment.*;
import com.amadeus.reader.EventSource;
import com.amadeus.reader.ResponseHandler;
import com.ets.fe.APIConfig;
import com.ets.fe.Application;
import com.ets.fe.accounts.gui.report.*;
import com.ets.fe.acdoc.gui.report.*;
import com.ets.fe.acdoc_o.gui.OtherInvoiceDlg;
import com.ets.fe.acdoc_o.gui.OtherInvoiceReportingFrame;
import com.ets.fe.accounts.gui.payment.OtherSalesBatchPayment;
import com.ets.fe.accounts.gui.payment.OtherSalesBatchPaymentReport;
import com.ets.fe.settings.model.AppSettings;
import com.ets.fe.client.gui.*;
import com.ets.fe.client.model.*;
import com.ets.fe.os.gui.OtherServiceFrame;
import com.ets.fe.accounts.gui.revenue.OtherServiceSaleReportFrame;
import com.ets.fe.pnr.gui.*;
import com.ets.fe.productivity.gui.UserProductivitylFrame;
import com.ets.fe.settings.gui.*;
import com.ets.fe.tools.gui.EmailFrame;
import com.ets.fe.util.Enums;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.Window;
import java.beans.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Yusuf
 */
public class Main extends JFrame implements PropertyChangeListener {

    private static boolean loginSuccess = false;
    private static DlgLogin dlgLogin;

    public static DlgLogin getDlgLogin() {
        return dlgLogin;
    }

    public static void setDlgLogin(DlgLogin aDlgLogin) {
        dlgLogin = aDlgLogin;
    }

    //private Application appSettings;
    //private APIConfig aPIConfig;
    private String taskType = "";

    public Main() {
        initComponents();
        initMenu();
        //aPIConfig = new APIConfig();
        int inset = 50;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(inset, inset,
                screenSize.width - inset * 2,
                screenSize.height - inset * 2);

        callDashBoard();
        startFileReading();

        //Make dragging a little faster but perhaps uglier.
        desktopPane.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);            
    }

    private void callDashBoard() {
        DashBoardFrame frame = new DashBoardFrame();
        try {
            frameAction(frame);
            frame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

//        SwingUtilities.invokeLater(new Runnable() {
//
//            @Override
//            public void run() {
//                DashBoardFrame frame = new DashBoardFrame();
//                frame.setVisible(true);
//                desktopPane.add(frame);
//                try {
//                    frame.setMaximum(true);
//                    frame.setSelected(true);
//                } catch (PropertyVetoException ex) {
//                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    public void startFileReading() {
        ResponseHandler respHandler = new ResponseHandler();
        EventSource evSrc = new EventSource();
        evSrc.addObserver(respHandler);
        Thread thread = new Thread(evSrc);
        thread.start();
        System.out.println("Observer started...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnNewCustomer = new javax.swing.JButton();
        btnNewOInvoice = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCashBook = new javax.swing.JButton();
        btnSalesInvoiceHistory = new javax.swing.JButton();
        btnPurchaseInvoiceHistory = new javax.swing.JButton();
        btnOtherInvoiceHistory = new javax.swing.JButton();
        btnUnpaidFlight = new javax.swing.JButton();
        btnTSBatchPayment = new javax.swing.JButton();
        btnOSBatchPayment = new javax.swing.JButton();
        btnTSBatchPaymentHistory = new javax.swing.JButton();
        btnOSBatchPaymentHistory = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        menuAirLine = new javax.swing.JMenuItem();
        menuAppSettings = new javax.swing.JMenuItem();
        menuCompanyProfile = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuTktDiscrepancy = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuClient = new javax.swing.JMenu();
        menuNewAgent = new javax.swing.JMenuItem();
        menuNewCustomer = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        menuAgentManagement = new javax.swing.JMenuItem();
        menuCustomerManagement = new javax.swing.JMenuItem();
        menuPnr = new javax.swing.JMenu();
        menuPnrHistory = new javax.swing.JMenuItem();
        menuGdsSaleReport = new javax.swing.JMenuItem();
        menuSegmentHistory = new javax.swing.JMenuItem();
        menuSales = new javax.swing.JMenu();
        menuClientAccounts = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuSalesInvoiceHistory = new javax.swing.JMenuItem();
        menuSDueAllAgent = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuTSBatchPaymentHistory = new javax.swing.JMenuItem();
        menuTSBatchPayment = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        menuUnpaidFlight = new javax.swing.JMenuItem();
        menuPurchase = new javax.swing.JMenu();
        menuPurchaseInvoiceHistory = new javax.swing.JMenuItem();
        menuPDueAllAgent = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuBSPBilling = new javax.swing.JMenuItem();
        menu3rdPartyBillPayment = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuVendorAccounts = new javax.swing.JMenuItem();
        menuOther = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuServiceManager = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuOtherInvoiceHistory = new javax.swing.JMenuItem();
        menuODueAllAgent = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menuOSBatchPayment = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuAccounts = new javax.swing.JMenu();
        menuCashBook = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        menuSaleReport = new javax.swing.JMenuItem();
        menuSaleReportOther = new javax.swing.JMenuItem();
        menuSaleReportAdditional = new javax.swing.JMenuItem();
        menuProductivity = new javax.swing.JMenu();
        menuUserProductivity = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/ETSLogo.png")).getImage());

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_20.png"))); // NOI18N
        btnHome.setToolTipText("Dashboard");
        btnHome.setPreferredSize(new java.awt.Dimension(45, 22));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);

        btnNewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newclient18.png"))); // NOI18N
        btnNewCustomer.setToolTipText("New Customer");
        btnNewCustomer.setFocusable(false);
        btnNewCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewCustomer.setMaximumSize(new java.awt.Dimension(45, 22));
        btnNewCustomer.setMinimumSize(new java.awt.Dimension(45, 22));
        btnNewCustomer.setPreferredSize(new java.awt.Dimension(45, 22));
        btnNewCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewCustomer);

        btnNewOInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/onewinv18.png"))); // NOI18N
        btnNewOInvoice.setToolTipText("New Other Invoice");
        btnNewOInvoice.setMaximumSize(new java.awt.Dimension(45, 22));
        btnNewOInvoice.setMinimumSize(new java.awt.Dimension(45, 22));
        btnNewOInvoice.setPreferredSize(new java.awt.Dimension(45, 22));
        btnNewOInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOInvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewOInvoice);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/discpr18.png"))); // NOI18N
        jButton2.setToolTipText("Ticketing Discrepency");
        jButton2.setPreferredSize(new java.awt.Dimension(45, 22));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        btnCashBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cashbook18.png"))); // NOI18N
        btnCashBook.setToolTipText("Cash Book");
        btnCashBook.setPreferredSize(new java.awt.Dimension(45, 22));
        btnCashBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnCashBook);

        btnSalesInvoiceHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TicketSalesHistory20.png"))); // NOI18N
        btnSalesInvoiceHistory.setToolTipText("Ticketing Sales Invoice History");
        btnSalesInvoiceHistory.setPreferredSize(new java.awt.Dimension(45, 22));
        btnSalesInvoiceHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesInvoiceHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalesInvoiceHistory);

        btnPurchaseInvoiceHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TicketPurchaseHistory20.png"))); // NOI18N
        btnPurchaseInvoiceHistory.setToolTipText("Thirdparty Purchase Invoice History");
        btnPurchaseInvoiceHistory.setPreferredSize(new java.awt.Dimension(45, 22));
        btnPurchaseInvoiceHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseInvoiceHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnPurchaseInvoiceHistory);

        btnOtherInvoiceHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/OtherSalesHistory20.png"))); // NOI18N
        btnOtherInvoiceHistory.setToolTipText("Other Sales Invoice History");
        btnOtherInvoiceHistory.setPreferredSize(new java.awt.Dimension(45, 22));
        btnOtherInvoiceHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtherInvoiceHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnOtherInvoiceHistory);

        btnUnpaidFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/unpaidflight20.png"))); // NOI18N
        btnUnpaidFlight.setToolTipText("Flight with Unpaid Invoice");
        btnUnpaidFlight.setPreferredSize(new java.awt.Dimension(45, 22));
        btnUnpaidFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnpaidFlightActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnpaidFlight);

        btnTSBatchPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TicketBatchPayment20.png"))); // NOI18N
        btnTSBatchPayment.setToolTipText("Ticketing Sales Batch Payment");
        btnTSBatchPayment.setPreferredSize(new java.awt.Dimension(45, 22));
        btnTSBatchPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSBatchPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnTSBatchPayment);

        btnOSBatchPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/OtherBatchPayment20.png"))); // NOI18N
        btnOSBatchPayment.setToolTipText("Other Sales Batch Payment");
        btnOSBatchPayment.setPreferredSize(new java.awt.Dimension(45, 22));
        btnOSBatchPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSBatchPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(btnOSBatchPayment);

        btnTSBatchPaymentHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/TicketPaymentHistory.png"))); // NOI18N
        btnTSBatchPaymentHistory.setToolTipText("Ticketing Sales Payment History");
        btnTSBatchPaymentHistory.setPreferredSize(new java.awt.Dimension(45, 22));
        btnTSBatchPaymentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTSBatchPaymentHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnTSBatchPaymentHistory);

        btnOSBatchPaymentHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/OtherPaymentHistory.png"))); // NOI18N
        btnOSBatchPaymentHistory.setToolTipText("Other Sales Payment History");
        btnOSBatchPaymentHistory.setPreferredSize(new java.awt.Dimension(45, 22));
        btnOSBatchPaymentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOSBatchPaymentHistoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnOSBatchPaymentHistory);

        jMenu1.setText("File");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        menuSettings.setText("Settings");

        menuAirLine.setText("BSP Com Settings");
        menuAirLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAirLineActionPerformed(evt);
            }
        });
        menuSettings.add(menuAirLine);

        menuAppSettings.setText("Application Settings");
        menuAppSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAppSettingsActionPerformed(evt);
            }
        });
        menuSettings.add(menuAppSettings);

        menuCompanyProfile.setText("Company Profile");
        menuCompanyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompanyProfileActionPerformed(evt);
            }
        });
        menuSettings.add(menuCompanyProfile);

        jMenuBar1.add(menuSettings);

        jMenu11.setText("Tools");

        menuTktDiscrepancy.setText("Ticketing Discrepancy");
        menuTktDiscrepancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTktDiscrepancyActionPerformed(evt);
            }
        });
        jMenu11.add(menuTktDiscrepancy);

        jMenuItem2.setText("Email");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem2);

        jMenuBar1.add(jMenu11);

        menuClient.setText("Client");

        menuNewAgent.setText("New Agent");
        menuNewAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewAgentActionPerformed(evt);
            }
        });
        menuClient.add(menuNewAgent);

        menuNewCustomer.setText("New Customer");
        menuNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewCustomerActionPerformed(evt);
            }
        });
        menuClient.add(menuNewCustomer);
        menuClient.add(jSeparator9);

        menuAgentManagement.setText("Agent Management");
        menuAgentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentManagementActionPerformed(evt);
            }
        });
        menuClient.add(menuAgentManagement);

        menuCustomerManagement.setText("Customer Management");
        menuCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomerManagementActionPerformed(evt);
            }
        });
        menuClient.add(menuCustomerManagement);

        jMenuBar1.add(menuClient);

        menuPnr.setText("Pnr");

        menuPnrHistory.setText("Pnr History");
        menuPnrHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPnrHistoryActionPerformed(evt);
            }
        });
        menuPnr.add(menuPnrHistory);

        menuGdsSaleReport.setText("GDS Sale Report");
        menuGdsSaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGdsSaleReportActionPerformed(evt);
            }
        });
        menuPnr.add(menuGdsSaleReport);

        menuSegmentHistory.setText("Segment History");
        menuSegmentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSegmentHistoryActionPerformed(evt);
            }
        });
        menuPnr.add(menuSegmentHistory);

        jMenuBar1.add(menuPnr);

        menuSales.setText("Sales");
        menuSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalesActionPerformed(evt);
            }
        });

        menuClientAccounts.setText("History: Client Accounts");
        menuClientAccounts.setToolTipText("Monthly Final Accounts Balance");
        menuClientAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientAccountsActionPerformed(evt);
            }
        });
        menuSales.add(menuClientAccounts);
        menuSales.add(jSeparator4);

        menuSalesInvoiceHistory.setText("History: Sales Invoice");
        menuSalesInvoiceHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalesInvoiceHistoryActionPerformed(evt);
            }
        });
        menuSales.add(menuSalesInvoiceHistory);

        menuSDueAllAgent.setText("Outstanding All Agent Summery");
        menuSDueAllAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSDueAllAgentActionPerformed(evt);
            }
        });
        menuSales.add(menuSDueAllAgent);
        menuSales.add(jSeparator1);

        menuTSBatchPaymentHistory.setText("History: Payment");
        menuTSBatchPaymentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTSBatchPaymentHistoryActionPerformed(evt);
            }
        });
        menuSales.add(menuTSBatchPaymentHistory);

        menuTSBatchPayment.setText("Batch Transaction");
        menuTSBatchPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTSBatchPaymentActionPerformed(evt);
            }
        });
        menuSales.add(menuTSBatchPayment);
        menuSales.add(jSeparator12);

        menuUnpaidFlight.setText("Unpaid Flight");
        menuUnpaidFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnpaidFlightActionPerformed(evt);
            }
        });
        menuSales.add(menuUnpaidFlight);

        jMenuBar1.add(menuSales);

        menuPurchase.setText("Purchase");
        menuPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPurchaseActionPerformed(evt);
            }
        });

        menuPurchaseInvoiceHistory.setText("History: Purchase Invoice");
        menuPurchaseInvoiceHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPurchaseInvoiceHistoryActionPerformed(evt);
            }
        });
        menuPurchase.add(menuPurchaseInvoiceHistory);

        menuPDueAllAgent.setText("Outstanding All Agent Summery");
        menuPDueAllAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPDueAllAgentActionPerformed(evt);
            }
        });
        menuPurchase.add(menuPDueAllAgent);
        menuPurchase.add(jSeparator2);

        menuBSPBilling.setText("Bill Payment: BSP");
        menuBSPBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBSPBillingActionPerformed(evt);
            }
        });
        menuPurchase.add(menuBSPBilling);

        menu3rdPartyBillPayment.setText("Bill Payment: 3rd Party");
        menu3rdPartyBillPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3rdPartyBillPaymentActionPerformed(evt);
            }
        });
        menuPurchase.add(menu3rdPartyBillPayment);
        menuPurchase.add(jSeparator3);

        jMenuItem7.setText("History: Bill Payment");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuPurchase.add(jMenuItem7);
        menuPurchase.add(jSeparator8);

        menuVendorAccounts.setText("History: Vendor Account");
        menuVendorAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendorAccountsActionPerformed(evt);
            }
        });
        menuPurchase.add(menuVendorAccounts);

        jMenuBar1.add(menuPurchase);

        menuOther.setText("Other");

        jMenuItem8.setText("New Invoice");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuOther.add(jMenuItem8);
        menuOther.add(jSeparator5);

        menuServiceManager.setText("Service Manager");
        menuServiceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiceManagerActionPerformed(evt);
            }
        });
        menuOther.add(menuServiceManager);
        menuOther.add(jSeparator10);

        jMenuItem11.setText("History: Client Accounts");
        jMenuItem11.setToolTipText("Monthly Final Accounts Balance");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        menuOther.add(jMenuItem11);
        menuOther.add(jSeparator6);

        menuOtherInvoiceHistory.setText("History: Other Invoice");
        menuOtherInvoiceHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOtherInvoiceHistoryActionPerformed(evt);
            }
        });
        menuOther.add(menuOtherInvoiceHistory);

        menuODueAllAgent.setText("Outstanding All Agent Summery");
        menuODueAllAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuODueAllAgentActionPerformed(evt);
            }
        });
        menuOther.add(menuODueAllAgent);
        menuOther.add(jSeparator11);

        menuOSBatchPayment.setText("Batch Transaction");
        menuOSBatchPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOSBatchPaymentActionPerformed(evt);
            }
        });
        menuOther.add(menuOSBatchPayment);

        jMenuItem10.setText("History: Payment");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuOther.add(jMenuItem10);

        jMenuBar1.add(menuOther);

        menuAccounts.setText("Accounts");

        menuCashBook.setText("Cash Book");
        menuCashBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCashBookActionPerformed(evt);
            }
        });
        menuAccounts.add(menuCashBook);
        menuAccounts.add(jSeparator7);

        menuSaleReport.setText("Sale Report: Ticketing");
        menuSaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaleReportActionPerformed(evt);
            }
        });
        menuAccounts.add(menuSaleReport);

        menuSaleReportOther.setText("Sale Report: Other Services");
        menuSaleReportOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaleReportOtherActionPerformed(evt);
            }
        });
        menuAccounts.add(menuSaleReportOther);

        menuSaleReportAdditional.setText("Sale Reprot: Additional Charges");
        menuAccounts.add(menuSaleReportAdditional);

        jMenuBar1.add(menuAccounts);

        menuProductivity.setText("Productivity");

        menuUserProductivity.setText("Productivity Report : Sales Person");
        menuUserProductivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUserProductivityActionPerformed(evt);
            }
        });
        menuProductivity.add(menuUserProductivity);

        jMenuBar1.add(menuProductivity);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPnrHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPnrHistoryActionPerformed
        frameAction(new PnrHistoryFrame());
    }//GEN-LAST:event_menuPnrHistoryActionPerformed

    private void menuAirLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAirLineActionPerformed
        AirlineManagementDlg dlg = new AirlineManagementDlg(this);
        dlg.showDialog();
    }//GEN-LAST:event_menuAirLineActionPerformed

    private void menuGdsSaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGdsSaleReportActionPerformed
        frameAction(new GDSSaleReportFrame());
    }//GEN-LAST:event_menuGdsSaleReportActionPerformed

    private void menuSegmentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSegmentHistoryActionPerformed
        frameAction(new SegmentReportFrame(desktopPane));
    }//GEN-LAST:event_menuSegmentHistoryActionPerformed

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        showCustomerDialogue();
    }//GEN-LAST:event_btnNewCustomerActionPerformed

    private void menuCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomerManagementActionPerformed
        frameAction(new CustomerFrame(desktopPane));
    }//GEN-LAST:event_menuCustomerManagementActionPerformed

    private void menuAgentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentManagementActionPerformed
        frameAction(new AgentFrame(desktopPane));
    }//GEN-LAST:event_menuAgentManagementActionPerformed

    private void menuServiceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiceManagerActionPerformed
        frameAction(new OtherServiceFrame(desktopPane));
    }//GEN-LAST:event_menuServiceManagerActionPerformed

    private void menuAppSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAppSettingsActionPerformed
        SettingsDlg dlg = new SettingsDlg(this);
        AppSettings settings = Application.getAppSettings();
        if (settings == null) {
            settings = new AppSettings();
        }
        if (dlg.showDialog(settings)) {
            SettingsTask task = new SettingsTask(settings);
            task.addPropertyChangeListener(this);
            task.execute();
            taskType = "SETTINGS";
        }
    }//GEN-LAST:event_menuAppSettingsActionPerformed

    private void menuCompanyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompanyProfileActionPerformed
        MainAgentDlg dlg = new MainAgentDlg(this);
        MainAgent agent = Application.getMainAgent();
        if (agent == null) {
            agent = new MainAgent();
        }
        if (dlg.showDialog(agent)) {
            MainAgentTask task = new MainAgentTask(agent);
            task.addPropertyChangeListener(this);
            task.execute();
            taskType = "SETTINGS";
        }
    }//GEN-LAST:event_menuCompanyProfileActionPerformed

    private void menuSalesInvoiceHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalesInvoiceHistoryActionPerformed
        frameAction(new TSalesInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuSalesInvoiceHistoryActionPerformed

    private void menuPurchaseInvoiceHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPurchaseInvoiceHistoryActionPerformed
        frameAction(new TPurchaseInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuPurchaseInvoiceHistoryActionPerformed

    private void menuTSBatchPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTSBatchPaymentActionPerformed
        frameAction(new TSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_menuTSBatchPaymentActionPerformed

    private void menu3rdPartyBillPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3rdPartyBillPaymentActionPerformed
        frameAction(new TPurchaseBatchPayment(desktopPane));
    }//GEN-LAST:event_menu3rdPartyBillPaymentActionPerformed

    private void menuTSBatchPaymentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTSBatchPaymentHistoryActionPerformed
        frameAction(new TSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_menuTSBatchPaymentHistoryActionPerformed

    private void menuSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalesActionPerformed

    }//GEN-LAST:event_menuSalesActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frameAction(new TPurchaseBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuClientAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientAccountsActionPerformed
        frameAction(new TSalesAccountsFrame(desktopPane));
    }//GEN-LAST:event_menuClientAccountsActionPerformed

    private void menuPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPurchaseActionPerformed

    }//GEN-LAST:event_menuPurchaseActionPerformed

    private void menuVendorAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendorAccountsActionPerformed
        frameAction(new TPurchaseAccountsFrame(desktopPane));
    }//GEN-LAST:event_menuVendorAccountsActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        OtherInvoiceDlg dlg = new OtherInvoiceDlg(this);
        dlg.showDialog(null);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuOtherInvoiceHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOtherInvoiceHistoryActionPerformed
        frameAction(new OtherInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuOtherInvoiceHistoryActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        frameAction(new OtherSalesAccountsFrame(desktopPane));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void menuOSBatchPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOSBatchPaymentActionPerformed
        frameAction(new OtherSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_menuOSBatchPaymentActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        frameAction(new OtherSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void menuCashBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCashBookActionPerformed
        frameAction(new CashBookFrame(desktopPane));
    }//GEN-LAST:event_menuCashBookActionPerformed

    private void menuSaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaleReportActionPerformed
        frameAction(new TicketSaleReportFrame(desktopPane));
    }//GEN-LAST:event_menuSaleReportActionPerformed

    private void menuSaleReportOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaleReportOtherActionPerformed
        frameAction(new OtherServiceSaleReportFrame(desktopPane));
    }//GEN-LAST:event_menuSaleReportOtherActionPerformed

    private void menuUserProductivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUserProductivityActionPerformed
        frameAction(new UserProductivitylFrame(desktopPane));
    }//GEN-LAST:event_menuUserProductivityActionPerformed

    private void menuUnpaidFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnpaidFlightActionPerformed
        frameAction(new OutstandingFlightReportingFrame(desktopPane));
    }//GEN-LAST:event_menuUnpaidFlightActionPerformed

    private void menuTktDiscrepancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTktDiscrepancyActionPerformed
        frameAction(new TicketingDiscrepancyFrame());
    }//GEN-LAST:event_menuTktDiscrepancyActionPerformed

    private void menuBSPBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBSPBillingActionPerformed
        frameAction(new BSPBillPayment(desktopPane));
    }//GEN-LAST:event_menuBSPBillingActionPerformed

    private void menuNewAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewAgentActionPerformed
        showAgentDialogue();
    }//GEN-LAST:event_menuNewAgentActionPerformed

    private void menuNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewCustomerActionPerformed
        showCustomerDialogue();
    }//GEN-LAST:event_menuNewCustomerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnNewOInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOInvoiceActionPerformed
        OtherInvoiceDlg dlg = new OtherInvoiceDlg(this);
        dlg.showDialog(null);
    }//GEN-LAST:event_btnNewOInvoiceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frameAction(new TicketingDiscrepancyFrame());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        callDashBoard();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnCashBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashBookActionPerformed
        frameAction(new CashBookFrame(desktopPane));
    }//GEN-LAST:event_btnCashBookActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        frameAction(new EmailFrame());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuSDueAllAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSDueAllAgentActionPerformed
        frameAction(new OutStandingAllAgentsFrame(Enums.SaleType.TKTSALES));
    }//GEN-LAST:event_menuSDueAllAgentActionPerformed

    private void menuPDueAllAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPDueAllAgentActionPerformed
        frameAction(new OutStandingAllAgentsFrame(Enums.SaleType.TKTPURCHASE));
    }//GEN-LAST:event_menuPDueAllAgentActionPerformed

    private void menuODueAllAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuODueAllAgentActionPerformed
        frameAction(new OutStandingAllAgentsFrame(Enums.SaleType.OTHERSALES));
    }//GEN-LAST:event_menuODueAllAgentActionPerformed

    private void btnOtherInvoiceHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtherInvoiceHistoryActionPerformed
        frameAction(new OtherInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_btnOtherInvoiceHistoryActionPerformed

    private void btnSalesInvoiceHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesInvoiceHistoryActionPerformed
        frameAction(new TSalesInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_btnSalesInvoiceHistoryActionPerformed

    private void btnPurchaseInvoiceHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseInvoiceHistoryActionPerformed
        frameAction(new TPurchaseInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_btnPurchaseInvoiceHistoryActionPerformed

    private void btnUnpaidFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnpaidFlightActionPerformed
         frameAction(new OutstandingFlightReportingFrame(desktopPane));
    }//GEN-LAST:event_btnUnpaidFlightActionPerformed

    private void btnTSBatchPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSBatchPaymentActionPerformed
        frameAction(new TSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_btnTSBatchPaymentActionPerformed

    private void btnOSBatchPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSBatchPaymentActionPerformed
        frameAction(new OtherSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_btnOSBatchPaymentActionPerformed

    private void btnTSBatchPaymentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTSBatchPaymentHistoryActionPerformed
        frameAction(new TSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_btnTSBatchPaymentHistoryActionPerformed

    private void btnOSBatchPaymentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOSBatchPaymentHistoryActionPerformed
        frameAction(new OtherSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_btnOSBatchPaymentHistoryActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getFullName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (Application.getLoggedOnUser() != null) {                    
                    new Main().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashBook;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JButton btnNewOInvoice;
    private javax.swing.JButton btnOSBatchPayment;
    private javax.swing.JButton btnOSBatchPaymentHistory;
    private javax.swing.JButton btnOtherInvoiceHistory;
    private javax.swing.JButton btnPurchaseInvoiceHistory;
    private javax.swing.JButton btnSalesInvoiceHistory;
    private javax.swing.JButton btnTSBatchPayment;
    private javax.swing.JButton btnTSBatchPaymentHistory;
    private javax.swing.JButton btnUnpaidFlight;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem menu3rdPartyBillPayment;
    private javax.swing.JMenu menuAccounts;
    private javax.swing.JMenuItem menuAgentManagement;
    private javax.swing.JMenuItem menuAirLine;
    private javax.swing.JMenuItem menuAppSettings;
    private javax.swing.JMenuItem menuBSPBilling;
    private javax.swing.JMenuItem menuCashBook;
    private javax.swing.JMenu menuClient;
    private javax.swing.JMenuItem menuClientAccounts;
    private javax.swing.JMenuItem menuCompanyProfile;
    private javax.swing.JMenuItem menuCustomerManagement;
    private javax.swing.JMenuItem menuGdsSaleReport;
    private javax.swing.JMenuItem menuNewAgent;
    private javax.swing.JMenuItem menuNewCustomer;
    private javax.swing.JMenuItem menuODueAllAgent;
    private javax.swing.JMenuItem menuOSBatchPayment;
    private javax.swing.JMenu menuOther;
    private javax.swing.JMenuItem menuOtherInvoiceHistory;
    private javax.swing.JMenuItem menuPDueAllAgent;
    private javax.swing.JMenu menuPnr;
    private javax.swing.JMenuItem menuPnrHistory;
    private javax.swing.JMenu menuProductivity;
    private javax.swing.JMenu menuPurchase;
    private javax.swing.JMenuItem menuPurchaseInvoiceHistory;
    private javax.swing.JMenuItem menuSDueAllAgent;
    private javax.swing.JMenuItem menuSaleReport;
    private javax.swing.JMenuItem menuSaleReportAdditional;
    private javax.swing.JMenuItem menuSaleReportOther;
    private javax.swing.JMenu menuSales;
    private javax.swing.JMenuItem menuSalesInvoiceHistory;
    private javax.swing.JMenuItem menuSegmentHistory;
    private javax.swing.JMenuItem menuServiceManager;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenuItem menuTSBatchPayment;
    private javax.swing.JMenuItem menuTSBatchPaymentHistory;
    private javax.swing.JMenuItem menuTktDiscrepancy;
    private javax.swing.JMenuItem menuUnpaidFlight;
    private javax.swing.JMenuItem menuUserProductivity;
    private javax.swing.JMenuItem menuVendorAccounts;
    // End of variables declaration//GEN-END:variables
@Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress".equals(evt.getPropertyName())) {
            int progress = (Integer) evt.getNewValue();
            //progressBar.setValue(progress);
            if (progress == 100) {
                if ("SETTINGS".equals(taskType)) {
                    Application.loadSettings();
                }
            }
        }
    }

    public void frameAction(JInternalFrame frame) {
        List<JInternalFrame> frames = Arrays.asList(desktopPane.getAllFrames());
        boolean exist = false;

        for (JInternalFrame f : frames) {
            if (f.getClass().getName().equals(frame.getClass().getName())) {
                frame = f;
                exist = true;
                break;
            }
        }

        if (exist) {
            frame.setVisible(true);
            frame.moveToFront();
            try {
                frame.setSelected(true);
            } catch (PropertyVetoException ex) {

            }
        } else {
            desktopPane.add(frame);
            try {
                frame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            frame.setVisible(true);
        }
    }

    private void showCustomerDialogue() {
        CustomerDlg customerDlg = new CustomerDlg(this);
        customerDlg.setTitle("New Customer");
        Customer newCustomer = new Customer();
        if (customerDlg.showDialog(newCustomer)) {
            CustomerTask task = new CustomerTask(newCustomer);
            task.execute();
        }
    }

    private void showAgentDialogue() {
        Window w = SwingUtilities.getWindowAncestor(this);
        Frame owner = w instanceof Frame ? (Frame) w : null;
        AgentDlg dlg = new AgentDlg(owner);
        dlg.setLocationRelativeTo(this);
        dlg.setTitle("New Agent");
        Agent agent = new Agent();
        if (dlg.showAgentDialog(agent)) {
            AgentTask task = new AgentTask(agent, "CREATE");
            task.execute();
        }
    }

    private void initMenu() {
        Application.getLoggedOnUser();
        if (Application.getLoggedOnUser().getUserType().getId() >= 2) {
            menuSettings.setVisible(true);
            
            menuSDueAllAgent.setVisible(true);
            menuPDueAllAgent.setVisible(true);
            menuODueAllAgent.setVisible(true);
            
            menuSaleReport.setVisible(true);
            menuSaleReportOther.setVisible(true);
            menuSaleReportAdditional.setVisible(true);
            
            menuProductivity.setVisible(true);
        } else {
            menuSettings.setVisible(false);
            
            menuSDueAllAgent.setVisible(false);
            menuPDueAllAgent.setVisible(false);
            menuODueAllAgent.setVisible(false);
            
            menuSaleReport.setVisible(false);
            menuSaleReportOther.setVisible(false);
            menuSaleReportAdditional.setVisible(false);
            
            menuProductivity.setVisible(false);
            
            if (Application.getLoggedOnUser().getUserType().getId() < 1) {
             menuClient.setVisible(false);
             menuPnr.setVisible(false);
             menuSales.setVisible(false);
             menuPurchase.setVisible(false);
             menuOther.setVisible(false);
             menuAccounts.setVisible(false);
             btnOSBatchPaymentHistory.setVisible(false);
             btnTSBatchPaymentHistory.setVisible(false);
             btnOSBatchPayment.setVisible(false);
             btnTSBatchPayment.setVisible(false);
             btnUnpaidFlight.setVisible(false);
             btnOtherInvoiceHistory.setVisible(false);
             btnPurchaseInvoiceHistory.setVisible(false);
             btnSalesInvoiceHistory.setVisible(false);
             btnCashBook.setVisible(false);
            }
        }
    }
}
