package com.ets.fe.a_main;

import com.ets.fe.client.task.AgentTask;
import com.ets.fe.client.task.CustomerTask;
import com.ets.fe.tools.gui.TicketingDiscrepancyFrame;
import com.ets.fe.accounts.gui.revenue.TicketSaleReportFrame;
import com.ets.fe.accounts.gui.payment.*;
import com.amadeus.reader.EventSource;
import com.amadeus.reader.ResponseHandler;
import com.ets.fe.APIConfig;
import com.ets.fe.Application;
import com.ets.fe.accounts.gui.report.*;
import com.ets.fe.acdoc.gui.report.*;
import com.ets.fe.acdoc_o.gui.OtherInvoiceDlg;
import com.ets.fe.acdoc_o.gui.OtherInvoiceReportingFrame;
import com.ets.fe.accounts.gui.payment.OtherSalesBatchPayment;
import com.ets.fe.accounts.gui.payment.OtherSalesBatchPaymentReport;
import com.ets.fe.settings.model.AppSettings;
import com.ets.fe.client.gui.*;
import com.ets.fe.client.model.*;
import com.ets.fe.os.gui.OtherServiceFrame;
import com.ets.fe.accounts.gui.revenue.OtherServiceSaleReportFrame;
import com.ets.fe.pnr.gui.*;
import com.ets.fe.productivity.gui.UserProductivitylFrame;
import com.ets.fe.settings.gui.*;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.Window;
import java.beans.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Yusuf
 */
public class Main extends JFrame implements PropertyChangeListener {

    private static boolean loginSuccess = false;
    private static DlgLogin dlgLogin;

    public static DlgLogin getDlgLogin() {
        return dlgLogin;
    }

    public static void setDlgLogin(DlgLogin aDlgLogin) {
        dlgLogin = aDlgLogin;
    }

    //private Application appSettings;
    private APIConfig aPIConfig;
    private String taskType = "";

    public Main() {
        initComponents();
        initMenu();
        aPIConfig = new APIConfig();
        int inset = 50;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(inset, inset,
                screenSize.width - inset * 2,
                screenSize.height - inset * 2);

        callDashBoard();
        startFileReading();

        //Make dragging a little faster but perhaps uglier.
        desktopPane.setDragMode(JDesktopPane.OUTLINE_DRAG_MODE);
    }

    private void callDashBoard() {
        DashBoardFrame frame = new DashBoardFrame();
        try {
            frameAction(frame);
            frame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

//        SwingUtilities.invokeLater(new Runnable() {
//
//            @Override
//            public void run() {
//                DashBoardFrame frame = new DashBoardFrame();
//                frame.setVisible(true);
//                desktopPane.add(frame);
//                try {
//                    frame.setMaximum(true);
//                    frame.setSelected(true);
//                } catch (PropertyVetoException ex) {
//                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
    }

    public void startFileReading() {
        ResponseHandler respHandler = new ResponseHandler();
        EventSource evSrc = new EventSource();
        evSrc.addObserver(respHandler);
        Thread thread = new Thread(evSrc);
        thread.start();
        System.out.println("Observer started...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnNewCustomer = new javax.swing.JButton();
        btnNewOInvoice = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnCashBook = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuSettings = new javax.swing.JMenu();
        menuAirLine = new javax.swing.JMenuItem();
        menuAppSettings = new javax.swing.JMenuItem();
        menuCompanyProfile = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuTktDiscrepancy = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuNewAgent = new javax.swing.JMenuItem();
        menuNewCustomer = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        menuAgentManagement = new javax.swing.JMenuItem();
        menuCustomerManagement = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuServiceManager = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuPnrHistory = new javax.swing.JMenuItem();
        menuGdsSaleReport = new javax.swing.JMenuItem();
        menuSegmentHistory = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuSalesInvoiceRpt = new javax.swing.JMenuItem();
        menuUnpaidFlight = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuBatchTransaction = new javax.swing.JMenuItem();
        menuBatchTransRpt = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuClientAccounts = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuPReporting = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuBSPBilling = new javax.swing.JMenuItem();
        menu3rdPartyBillPayment = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuVendorAccounts = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuDueOSalesInvoice = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 2));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_18.png"))); // NOI18N
        jButton1.setToolTipText("Dashboard");
        jButton1.setPreferredSize(new java.awt.Dimension(45, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        btnNewCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/newclient18.png"))); // NOI18N
        btnNewCustomer.setToolTipText("New Customer");
        btnNewCustomer.setFocusable(false);
        btnNewCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewCustomer.setMaximumSize(new java.awt.Dimension(45, 22));
        btnNewCustomer.setMinimumSize(new java.awt.Dimension(45, 22));
        btnNewCustomer.setPreferredSize(new java.awt.Dimension(45, 22));
        btnNewCustomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCustomerActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewCustomer);

        btnNewOInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/onewinv18.png"))); // NOI18N
        btnNewOInvoice.setToolTipText("New Other Invoice");
        btnNewOInvoice.setMaximumSize(new java.awt.Dimension(45, 22));
        btnNewOInvoice.setMinimumSize(new java.awt.Dimension(45, 22));
        btnNewOInvoice.setPreferredSize(new java.awt.Dimension(45, 22));
        btnNewOInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewOInvoiceActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewOInvoice);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/discpr18.png"))); // NOI18N
        jButton2.setToolTipText("Ticketing Discrepency");
        jButton2.setPreferredSize(new java.awt.Dimension(45, 22));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        btnCashBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cashbook18.png"))); // NOI18N
        btnCashBook.setToolTipText("Cash Book");
        btnCashBook.setPreferredSize(new java.awt.Dimension(45, 22));
        btnCashBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashBookActionPerformed(evt);
            }
        });
        jPanel1.add(btnCashBook);

        jMenu1.setText("File");

        jMenuItem1.setText("Log Out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("Exit");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        menuSettings.setText("Settings");

        menuAirLine.setText("BSP Com Settings");
        menuAirLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAirLineActionPerformed(evt);
            }
        });
        menuSettings.add(menuAirLine);

        menuAppSettings.setText("Application Settings");
        menuAppSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAppSettingsActionPerformed(evt);
            }
        });
        menuSettings.add(menuAppSettings);

        menuCompanyProfile.setText("Company Profile");
        menuCompanyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCompanyProfileActionPerformed(evt);
            }
        });
        menuSettings.add(menuCompanyProfile);

        jMenuBar1.add(menuSettings);

        jMenu11.setText("Tools");

        menuTktDiscrepancy.setText("Ticketing Discrepancy");
        menuTktDiscrepancy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTktDiscrepancyActionPerformed(evt);
            }
        });
        jMenu11.add(menuTktDiscrepancy);

        jMenuBar1.add(jMenu11);

        jMenu5.setText("Client");

        menuNewAgent.setText("New Agent");
        menuNewAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewAgentActionPerformed(evt);
            }
        });
        jMenu5.add(menuNewAgent);

        menuNewCustomer.setText("New Customer");
        menuNewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewCustomerActionPerformed(evt);
            }
        });
        jMenu5.add(menuNewCustomer);
        jMenu5.add(jSeparator9);

        menuAgentManagement.setText("Agent Management");
        menuAgentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgentManagementActionPerformed(evt);
            }
        });
        jMenu5.add(menuAgentManagement);

        menuCustomerManagement.setText("Customer Management");
        menuCustomerManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCustomerManagementActionPerformed(evt);
            }
        });
        jMenu5.add(menuCustomerManagement);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Services");

        menuServiceManager.setText("Service Manager");
        menuServiceManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServiceManagerActionPerformed(evt);
            }
        });
        jMenu2.add(menuServiceManager);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Pnr");

        menuPnrHistory.setText("Pnr History");
        menuPnrHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPnrHistoryActionPerformed(evt);
            }
        });
        jMenu3.add(menuPnrHistory);

        menuGdsSaleReport.setText("GDS Sale Report");
        menuGdsSaleReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGdsSaleReportActionPerformed(evt);
            }
        });
        jMenu3.add(menuGdsSaleReport);

        menuSegmentHistory.setText("Segment History");
        menuSegmentHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSegmentHistoryActionPerformed(evt);
            }
        });
        jMenu3.add(menuSegmentHistory);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Sales");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        menuSalesInvoiceRpt.setText("Report: Sales Invoice");
        menuSalesInvoiceRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalesInvoiceRptActionPerformed(evt);
            }
        });
        jMenu6.add(menuSalesInvoiceRpt);

        menuUnpaidFlight.setText("Report: Outstanding Flight");
        menuUnpaidFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUnpaidFlightActionPerformed(evt);
            }
        });
        jMenu6.add(menuUnpaidFlight);
        jMenu6.add(jSeparator1);

        menuBatchTransaction.setText("Batch Transaction");
        menuBatchTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBatchTransactionActionPerformed(evt);
            }
        });
        jMenu6.add(menuBatchTransaction);

        menuBatchTransRpt.setText("History: Batch Transaction");
        menuBatchTransRpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBatchTransRptActionPerformed(evt);
            }
        });
        jMenu6.add(menuBatchTransRpt);
        jMenu6.add(jSeparator4);

        menuClientAccounts.setText("History: Client Account");
        menuClientAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientAccountsActionPerformed(evt);
            }
        });
        jMenu6.add(menuClientAccounts);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Purchase");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        menuPReporting.setText("Purchase Invoice: Report");
        menuPReporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPReportingActionPerformed(evt);
            }
        });
        jMenu7.add(menuPReporting);
        jMenu7.add(jSeparator2);

        menuBSPBilling.setText("Bill Payment: BSP");
        menuBSPBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBSPBillingActionPerformed(evt);
            }
        });
        jMenu7.add(menuBSPBilling);

        menu3rdPartyBillPayment.setText("Bill Payment: 3rd Party");
        menu3rdPartyBillPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3rdPartyBillPaymentActionPerformed(evt);
            }
        });
        jMenu7.add(menu3rdPartyBillPayment);
        jMenu7.add(jSeparator3);

        jMenuItem7.setText("History: Bill Payment");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);
        jMenu7.add(jSeparator8);

        menuVendorAccounts.setText("History: Vendor Account");
        menuVendorAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVendorAccountsActionPerformed(evt);
            }
        });
        jMenu7.add(menuVendorAccounts);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Other");

        jMenuItem8.setText("New Invoice");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem8);
        jMenu8.add(jSeparator5);

        menuDueOSalesInvoice.setText("Other Invoice: Report");
        menuDueOSalesInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDueOSalesInvoiceActionPerformed(evt);
            }
        });
        jMenu8.add(menuDueOSalesInvoice);

        jMenuItem9.setText("Batch Transaction");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("History: Batch Transaction");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);
        jMenu8.add(jSeparator6);

        jMenuItem11.setText("History: Client Account");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Accounts");

        jMenuItem12.setText("Cash Book");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem12);
        jMenu9.add(jSeparator7);

        jMenuItem13.setText("Sale Report: Ticketing");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem13);

        jMenuItem15.setText("Sale Report: Other Services");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem15);

        jMenuItem14.setText("Sale Reprot: Additional Charges");
        jMenu9.add(jMenuItem14);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Productivity");

        jMenuItem16.setText("Productivity Report : Sales Person");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem16);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPnrHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPnrHistoryActionPerformed
        frameAction(new PnrHistoryFrame());
    }//GEN-LAST:event_menuPnrHistoryActionPerformed

    private void menuAirLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAirLineActionPerformed
        AirlineManagementDlg dlg = new AirlineManagementDlg(this);
        dlg.showDialog();
    }//GEN-LAST:event_menuAirLineActionPerformed

    private void menuGdsSaleReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGdsSaleReportActionPerformed
        frameAction(new GDSSaleReportFrame());
    }//GEN-LAST:event_menuGdsSaleReportActionPerformed

    private void menuSegmentHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSegmentHistoryActionPerformed
        frameAction(new SegmentReportFrame(desktopPane));
    }//GEN-LAST:event_menuSegmentHistoryActionPerformed

    private void btnNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCustomerActionPerformed
        showCustomerDialogue();
    }//GEN-LAST:event_btnNewCustomerActionPerformed

    private void menuCustomerManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCustomerManagementActionPerformed
        frameAction(new CustomerFrame(desktopPane));
    }//GEN-LAST:event_menuCustomerManagementActionPerformed

    private void menuAgentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgentManagementActionPerformed
        frameAction(new AgentFrame(desktopPane));
    }//GEN-LAST:event_menuAgentManagementActionPerformed

    private void menuServiceManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServiceManagerActionPerformed
        frameAction(new OtherServiceFrame(desktopPane));
    }//GEN-LAST:event_menuServiceManagerActionPerformed

    private void menuAppSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAppSettingsActionPerformed
        SettingsDlg dlg = new SettingsDlg(this);
        AppSettings settings = Application.getAppSettings();
        if (settings == null) {
            settings = new AppSettings();
        }
        if (dlg.showDialog(settings)) {
            SettingsTask task = new SettingsTask(settings);
            task.addPropertyChangeListener(this);
            task.execute();
            taskType = "SETTINGS";
        }
    }//GEN-LAST:event_menuAppSettingsActionPerformed

    private void menuCompanyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCompanyProfileActionPerformed
        MainAgentDlg dlg = new MainAgentDlg(this);
        MainAgent agent = Application.getMainAgent();
        if (agent == null) {
            agent = new MainAgent();
        }
        if (dlg.showDialog(agent)) {
            MainAgentTask task = new MainAgentTask(agent);
            task.addPropertyChangeListener(this);
            task.execute();
            taskType = "SETTINGS";
        }
    }//GEN-LAST:event_menuCompanyProfileActionPerformed

    private void menuSalesInvoiceRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalesInvoiceRptActionPerformed
        frameAction(new TSalesInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuSalesInvoiceRptActionPerformed

    private void menuPReportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPReportingActionPerformed
        frameAction(new TPurchaseInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuPReportingActionPerformed

    private void menuBatchTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBatchTransactionActionPerformed
        frameAction(new TSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_menuBatchTransactionActionPerformed

    private void menu3rdPartyBillPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3rdPartyBillPaymentActionPerformed
        frameAction(new TPurchaseBatchPayment(desktopPane));
    }//GEN-LAST:event_menu3rdPartyBillPaymentActionPerformed

    private void menuBatchTransRptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBatchTransRptActionPerformed
        frameAction(new TSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_menuBatchTransRptActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        frameAction(new TPurchaseBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void menuClientAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientAccountsActionPerformed
        frameAction(new TSalesAccountsFrame(desktopPane));
    }//GEN-LAST:event_menuClientAccountsActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed

    }//GEN-LAST:event_jMenu7ActionPerformed

    private void menuVendorAccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVendorAccountsActionPerformed
        frameAction(new TPurchaseAccountsFrame(desktopPane));
    }//GEN-LAST:event_menuVendorAccountsActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        OtherInvoiceDlg dlg = new OtherInvoiceDlg(this);
        dlg.showDialog(null);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void menuDueOSalesInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDueOSalesInvoiceActionPerformed
        frameAction(new OtherInvoiceReportingFrame(desktopPane));
    }//GEN-LAST:event_menuDueOSalesInvoiceActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        frameAction(new OtherSalesAccountsFrame(desktopPane));
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        frameAction(new OtherSalesBatchPayment(desktopPane));
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        frameAction(new OtherSalesBatchPaymentReport(desktopPane));
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        frameAction(new CashBookFrame(desktopPane));
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        frameAction(new TicketSaleReportFrame(desktopPane));
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        frameAction(new OtherServiceSaleReportFrame(desktopPane));
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        frameAction(new UserProductivitylFrame(desktopPane));
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void menuUnpaidFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUnpaidFlightActionPerformed
        frameAction(new OutstandingFlightReportingFrame(desktopPane));
    }//GEN-LAST:event_menuUnpaidFlightActionPerformed

    private void menuTktDiscrepancyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTktDiscrepancyActionPerformed
        frameAction(new TicketingDiscrepancyFrame());
    }//GEN-LAST:event_menuTktDiscrepancyActionPerformed

    private void menuBSPBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBSPBillingActionPerformed
        frameAction(new BSPBillPayment(desktopPane));
    }//GEN-LAST:event_menuBSPBillingActionPerformed

    private void menuNewAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewAgentActionPerformed
        showAgentDialogue();
    }//GEN-LAST:event_menuNewAgentActionPerformed

    private void menuNewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewCustomerActionPerformed
        showCustomerDialogue();
    }//GEN-LAST:event_menuNewCustomerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnNewOInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewOInvoiceActionPerformed
        OtherInvoiceDlg dlg = new OtherInvoiceDlg(this);
        dlg.showDialog(null);
    }//GEN-LAST:event_btnNewOInvoiceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frameAction(new TicketingDiscrepancyFrame());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        callDashBoard();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCashBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashBookActionPerformed
        frameAction(new CashBookFrame(desktopPane));
    }//GEN-LAST:event_btnCashBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getFullName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getFullName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                if (Application.getLoggedOnUser() != null) {
                    System.out.println("Accessed>>>>>");
                    new Main().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashBook;
    private javax.swing.JButton btnNewCustomer;
    private javax.swing.JButton btnNewOInvoice;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenuItem menu3rdPartyBillPayment;
    private javax.swing.JMenuItem menuAgentManagement;
    private javax.swing.JMenuItem menuAirLine;
    private javax.swing.JMenuItem menuAppSettings;
    private javax.swing.JMenuItem menuBSPBilling;
    private javax.swing.JMenuItem menuBatchTransRpt;
    private javax.swing.JMenuItem menuBatchTransaction;
    private javax.swing.JMenuItem menuClientAccounts;
    private javax.swing.JMenuItem menuCompanyProfile;
    private javax.swing.JMenuItem menuCustomerManagement;
    private javax.swing.JMenuItem menuDueOSalesInvoice;
    private javax.swing.JMenuItem menuGdsSaleReport;
    private javax.swing.JMenuItem menuNewAgent;
    private javax.swing.JMenuItem menuNewCustomer;
    private javax.swing.JMenuItem menuPReporting;
    private javax.swing.JMenuItem menuPnrHistory;
    private javax.swing.JMenuItem menuSalesInvoiceRpt;
    private javax.swing.JMenuItem menuSegmentHistory;
    private javax.swing.JMenuItem menuServiceManager;
    private javax.swing.JMenu menuSettings;
    private javax.swing.JMenuItem menuTktDiscrepancy;
    private javax.swing.JMenuItem menuUnpaidFlight;
    private javax.swing.JMenuItem menuVendorAccounts;
    // End of variables declaration//GEN-END:variables
@Override
    public void propertyChange(PropertyChangeEvent evt) {
        if ("progress".equals(evt.getPropertyName())) {
            int progress = (Integer) evt.getNewValue();
            //progressBar.setValue(progress);
            if (progress == 100) {
                if ("SETTINGS".equals(taskType)) {
                    Application.loadSettings();
                }
            }
        }
    }

    public void frameAction(JInternalFrame frame) {
        List<JInternalFrame> frames = Arrays.asList(desktopPane.getAllFrames());
        boolean exist = false;

        for (JInternalFrame f : frames) {
            if (f.getClass().getName().equals(frame.getClass().getName())) {
                frame = f;
                exist = true;
                break;
            }
        }

        if (exist) {
            frame.setVisible(true);
            frame.moveToFront();
            try {
                frame.setSelected(true);
            } catch (PropertyVetoException ex) {

            }
        } else {
            desktopPane.add(frame);
            try {
                frame.setSelected(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            frame.setVisible(true);
        }
    }

    private void showCustomerDialogue() {
        CustomerDlg customerDlg = new CustomerDlg(this);
        customerDlg.setTitle("New Customer");
        Customer newCustomer = new Customer();
        if (customerDlg.showDialog(newCustomer)) {
            CustomerTask task = new CustomerTask(newCustomer);
            task.execute();
        }
    }

    private void showAgentDialogue() {
        Window w = SwingUtilities.getWindowAncestor(this);
        Frame owner = w instanceof Frame ? (Frame) w : null;
        AgentDlg dlg = new AgentDlg(owner);
        dlg.setLocationRelativeTo(this);
        dlg.setTitle("New Agent");
        Agent agent = new Agent();
        if (dlg.showAgentDialog(agent)) {
            AgentTask task = new AgentTask(agent);
            task.execute();
        }
    }

    private void initMenu() {
        Application.getLoggedOnUser();
        if (Application.getLoggedOnUser().isAdmin()) {
            menuSettings.setVisible(true);
            
        } else {
            menuSettings.setVisible(false);
        }
    }
}
